import type { CounselingScript } from './types'

export const SHARED_COUNSELING_SCRIPTS: CounselingScript[] = [
  {
    scriptId: 'body_discomfort_support',
    title: '몸이 불편할 때',
    domain: 'body',
    weight: 3,
    contextLine: '잠깐 쉬어가도 돼.',
    fallbackEndingLine: '필요하면 다시 와.',
    startNodeId: 'body_01',
    nodes: {
      body_01: {
        nodeId: 'body_01',
        questionText: '지금 몸은 어때?',
        choices: [
          {
            choiceIntentId: 'body_okay_now',
            text: '괜찮아요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['positive_body_state'],
            responseLines: ['좋아. 지금은 괜찮구나.', '그래도 불편해지면 바로 말해도 돼.'],
            endingLines: ['천천히 둘러보고 와.', '필요하면 다시 들러.'],
          },
          {
            choiceIntentId: 'body_tired_easy',
            text: '금방 힘이 빠져요',
            nextNodeId: 'body_tired_02',
            intensity: 2,
            concernFlags: ['fatigue_present', 'body_discomfort'],
            protectiveFactors: ['body_state_named'],
            responseLines: ['그럴 때 있지.', '힘이 빠지면 잠깐 쉬어도 돼.'],
          },
          {
            choiceIntentId: 'body_pain_worry',
            text: '아픈 게 걱정돼요',
            nextNodeId: 'body_pain_02',
            intensity: 3,
            concernFlags: ['pain_concern', 'procedure_fear'],
            protectiveFactors: ['can_name_fear'],
            responseLines: [
              '아픈 게 걱정되면 혼자 참지 않아도 돼.',
              '말하기 어려우면 손으로 알려도 괜찮아.',
            ],
          },
        ],
      },
      body_tired_02: {
        nodeId: 'body_tired_02',
        questionText: '그럴 땐 어떻게 쉬고 싶어?',
        choices: [
          {
            choiceIntentId: 'body_rest_quiet',
            text: '조용히 있고 싶어요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 1,
            concernFlags: ['needs_rest'],
            protectiveFactors: ['sets_boundary', 'rest_need_named'],
            responseLines: ['조용히 있는 것도 좋아.', '말을 많이 하지 않아도 괜찮아.'],
            endingLines: ['오늘은 천천히 가도 괜찮아.', '쉬고 싶으면 다시 와.'],
          },
          {
            choiceIntentId: 'body_family_near',
            text: '가족 옆에 있고 싶어요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['family_support_preference', 'support_need_named'],
            responseLines: ['편한 사람 곁에 있으면 조금 쉬기 쉬워.'],
            endingLines: ['가족 옆에서 쉬어도 괜찮아.', '나중에 또 놀러 와.'],
          },
          {
            choiceIntentId: 'body_tell_adult',
            text: '어른에게 말할래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['support_seeking', 'adult_support_preference'],
            responseLines: ['좋아. 가까운 어른에게 말하면 같이 도와줄 수 있어.'],
            endingLines: ['혼자 참지 않아도 돼.', '필요하면 다시 와.'],
          },
        ],
      },
      body_pain_02: {
        nodeId: 'body_pain_02',
        questionText: '아플 때는 어떻게 알려줄까?',
        choices: [
          {
            choiceIntentId: 'pain_tell_teacher',
            text: '선생님께 말할래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['medical_support_preference', 'support_seeking'],
            responseLines: ['선생님께 알려주면 도와줄 수 있어.', '작은 아픔도 말해도 괜찮아.'],
            endingLines: ['좋아, 혼자 참지 않아도 돼.', '언제든 다시 와.'],
          },
          {
            choiceIntentId: 'pain_point_place',
            text: '아픈 곳을 가리킬래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 1,
            concernFlags: ['prefers_nonverbal_expression'],
            protectiveFactors: ['alternative_expression', 'body_state_named'],
            responseLines: [
              '말이 잘 안 나올 때는 손으로 알려줘도 돼.',
              '그것도 충분히 좋은 방법이야.',
            ],
            endingLines: ['네 방식대로 알려줘도 괜찮아.', '다음에 또 들러줘.'],
          },
          {
            choiceIntentId: 'pain_hold_hand',
            text: '손을 잡아줬으면 해요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 1,
            concernFlags: ['needs_comfort'],
            protectiveFactors: ['comfort_preference_named', 'support_need_named'],
            responseLines: ['손을 잡아달라고 부탁해도 괜찮아.', '그게 힘이 될 때도 있어.'],
            endingLines: ['도움을 받아도 괜찮아.', '나는 여기 있을게.'],
          },
        ],
      },
    },
  },
  {
    scriptId: 'procedure_worry_support',
    title: '검사나 주사 전 걱정',
    domain: 'pain',
    weight: 2,
    contextLine: '혹시 검사나 주사 생각이 났어?',
    fallbackEndingLine: '걱정되면 다시 와도 돼.',
    startNodeId: 'procedure_01',
    nodes: {
      procedure_01: {
        nodeId: 'procedure_01',
        questionText: '검사나 주사 생각하면 어때?',
        choices: [
          {
            choiceIntentId: 'procedure_pain_fear',
            text: '아플까 봐 걱정돼요',
            nextNodeId: 'procedure_support_02',
            intensity: 3,
            concernFlags: ['procedure_fear', 'pain_concern'],
            protectiveFactors: ['can_name_fear'],
            responseLines: ['그럴 수 있어.', '아플까 봐 걱정될 때가 있지.'],
          },
          {
            choiceIntentId: 'procedure_unknown_fear',
            text: '어떻게 하는지 모르겠어요',
            nextNodeId: 'procedure_info_02',
            intensity: 2,
            concernFlags: ['uncertainty', 'information_need'],
            protectiveFactors: ['uncertainty_named'],
            responseLines: ['모르면 더 걱정될 수 있어.', '물어봐도 괜찮아.'],
          },
          {
            choiceIntentId: 'procedure_now_okay',
            text: '지금은 괜찮아요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['positive_mood'],
            responseLines: ['좋아. 지금은 괜찮구나.', '필요하면 나중에 다시 말해도 돼.'],
            endingLines: ['오늘은 여기까지 해도 괜찮아.', '다음에 또 놀러 와.'],
          },
        ],
      },
      procedure_support_02: {
        nodeId: 'procedure_support_02',
        questionText: '걱정될 때 누가 옆에 있으면 좋아?',
        choices: [
          {
            choiceIntentId: 'procedure_family_near',
            text: '가족이 옆에 있으면 좋아요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['family_support_preference', 'support_need_named'],
            responseLines: ['가족 곁에 있으면 마음이 조금 편해질 수 있어.'],
            endingLines: ['걱정되면 다시 와도 돼.', '나는 여기 있을게.'],
          },
          {
            choiceIntentId: 'procedure_teacher_near',
            text: '선생님이 옆에 있으면 좋아요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['medical_support_preference', 'support_need_named'],
            responseLines: ['선생님이 옆에서 알려주면 조금 안심될 수 있어.'],
            endingLines: ['궁금한 건 물어봐도 괜찮아.', '다음에 또 이야기하자.'],
          },
          {
            choiceIntentId: 'procedure_hold_hand',
            text: '손을 잡아줬으면 해요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 1,
            concernFlags: ['needs_comfort'],
            protectiveFactors: ['comfort_preference_named'],
            responseLines: ['손을 잡아달라고 말해도 괜찮아.', '그게 마음을 편하게 해줄 수 있어.'],
            endingLines: ['도움을 부탁해도 괜찮아.', '편할 때 다시 와.'],
          },
        ],
      },
      procedure_info_02: {
        nodeId: 'procedure_info_02',
        questionText: '모를 때는 어떻게 하면 좋을까?',
        choices: [
          {
            choiceIntentId: 'procedure_ask_teacher',
            text: '선생님께 물어볼래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['information_seeking', 'medical_support_preference'],
            responseLines: ['좋아. 모른다고 말하고 물어보는 건 괜찮은 일이야.'],
            endingLines: ['궁금하면 물어봐도 돼.', '다음에 또 들러줘.'],
          },
          {
            choiceIntentId: 'procedure_family_ask',
            text: '가족이랑 물어볼래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['family_support_preference', 'information_seeking'],
            responseLines: ['가족이랑 같이 물어보면 더 든든할 수 있어.'],
            endingLines: ['같이 물어보는 것도 좋은 방법이야.', '나중에 또 말해줘.'],
          },
          {
            choiceIntentId: 'procedure_draw_question',
            text: '그림으로 물어볼래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: ['prefers_nonverbal_expression'],
            protectiveFactors: ['alternative_expression', 'creative_expression'],
            responseLines: ['말로 하기 어려우면 그림으로 물어봐도 괜찮아.'],
            endingLines: ['네 방식대로 물어봐도 돼.', '언제든 다시 와.'],
          },
        ],
      },
    },
  },
  {
    scriptId: 'fatigue_rest_support',
    title: '피로와 휴식',
    domain: 'fatigue',
    weight: 3,
    contextLine: '잠깐 쉬어가도 좋아.',
    fallbackEndingLine: '편할 때 다시 와.',
    startNodeId: 'fatigue_01',
    nodes: {
      fatigue_01: {
        nodeId: 'fatigue_01',
        questionText: '지금 얼마나 피곤해?',
        choices: [
          {
            choiceIntentId: 'fatigue_okay',
            text: '괜찮아요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['positive_body_state'],
            responseLines: ['좋아. 지금은 괜찮구나.', '그래도 피곤해지면 쉬어도 돼.'],
            endingLines: ['네 속도대로 가도 괜찮아.', '다음에 또 쉬러 와.'],
          },
          {
            choiceIntentId: 'fatigue_little',
            text: '조금 쉬고 싶어요',
            nextNodeId: 'fatigue_rest_02',
            intensity: 1,
            concernFlags: ['fatigue_present', 'needs_rest'],
            protectiveFactors: ['rest_need_named'],
            responseLines: ['그럴 때 있지.', '조금 쉬어도 괜찮아.'],
          },
          {
            choiceIntentId: 'fatigue_much',
            text: '많이 쉬고 싶어요',
            nextNodeId: 'fatigue_rest_02',
            intensity: 3,
            concernFlags: ['fatigue_high', 'needs_rest'],
            protectiveFactors: ['body_state_named', 'rest_need_named'],
            responseLines: ['그럴 땐 많이 쉬어도 괜찮아.', '오늘은 천천히 가자.'],
          },
        ],
      },
      fatigue_rest_02: {
        nodeId: 'fatigue_rest_02',
        questionText: '어떻게 쉬고 싶어?',
        choices: [
          {
            choiceIntentId: 'rest_quiet',
            text: '조용히 있을래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 1,
            concernFlags: ['needs_rest'],
            protectiveFactors: ['sets_boundary'],
            responseLines: ['조용한 시간도 좋은 쉼이야.', '말을 많이 하지 않아도 괜찮아.'],
            endingLines: ['오늘은 천천히 쉬어가자.', '나중에 또 와.'],
          },
          {
            choiceIntentId: 'rest_close_eyes',
            text: '눈을 감고 있을래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 1,
            concernFlags: ['fatigue_present'],
            protectiveFactors: ['self_care_action', 'rest_need_named'],
            responseLines: ['눈을 잠깐 감는 것도 몸을 쉬게 해줄 수 있어.'],
            endingLines: ['잠깐 쉬어도 괜찮아.', '편할 때 다시 놀러 와.'],
          },
          {
            choiceIntentId: 'rest_near_family',
            text: '가족 옆에 있을래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['family_support_preference', 'support_need_named'],
            responseLines: ['편한 사람 곁에 있으면 마음도 쉬기 쉬워.'],
            endingLines: ['편한 곳에서 쉬어도 괜찮아.', '나는 여기 있을게.'],
          },
        ],
      },
    },
  },
  {
    scriptId: 'family_worry_support',
    title: '가족 생각',
    domain: 'family',
    weight: 2,
    contextLine: '가족 생각이 나는 날도 있지.',
    fallbackEndingLine: '나는 여기 있을게.',
    startNodeId: 'family_01',
    nodes: {
      family_01: {
        nodeId: 'family_01',
        questionText: '가족 생각이 나면 어때?',
        choices: [
          {
            choiceIntentId: 'family_miss',
            text: '보고 싶어요',
            nextNodeId: 'family_miss_02',
            intensity: 2,
            concernFlags: ['family_worry', 'separation_distress'],
            protectiveFactors: ['relationship_named'],
            responseLines: ['보고 싶을 때가 있지.', '그럴 땐 어떻게 전하고 싶어?'],
          },
          {
            choiceIntentId: 'family_worry',
            text: '걱정돼요',
            nextNodeId: 'family_worry_02',
            intensity: 3,
            concernFlags: ['parent_concern', 'family_worry'],
            protectiveFactors: ['empathy', 'relationship_named'],
            responseLines: ['가족이 걱정될 때도 있지.', '혼자만 걱정하지 않아도 돼.'],
          },
          {
            choiceIntentId: 'family_okay',
            text: '지금은 괜찮아요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['positive_family_state'],
            responseLines: ['좋아. 지금은 괜찮구나.', '생각나면 나중에 다시 말해도 돼.'],
            endingLines: ['언제든 놀러 와.', '나는 여기 있을게.'],
          },
        ],
      },
      family_miss_02: {
        nodeId: 'family_miss_02',
        questionText: '가족에게 뭐라고 해보고 싶어?',
        choices: [
          {
            choiceIntentId: 'family_say_miss',
            text: '보고 싶다고 말할래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['verbal_expression', 'family_support_preference'],
            responseLines: ['짧게 말해도 마음이 전해질 수 있어.'],
            endingLines: ['그 마음은 천천히 전해도 돼.', '다음에 또 이야기하자.'],
          },
          {
            choiceIntentId: 'family_draw_picture',
            text: '그림으로 전할래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: ['prefers_nonverbal_expression'],
            protectiveFactors: ['creative_expression', 'alternative_expression'],
            responseLines: ['그림은 말보다 편할 때가 있어.'],
            endingLines: ['그림으로 전해도 괜찮아.', '편할 때 또 와.'],
          },
          {
            choiceIntentId: 'family_stay_near',
            text: '그냥 옆에 있고 싶어요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 1,
            concernFlags: ['needs_connection'],
            protectiveFactors: ['support_need_named', 'family_support_preference'],
            responseLines: ['말하지 않아도 곁에 있는 것만으로 힘이 될 때가 있어.'],
            endingLines: ['그냥 곁에 있어도 괜찮아.', '나는 여기 있을게.'],
          },
        ],
      },
      family_worry_02: {
        nodeId: 'family_worry_02',
        questionText: '그 마음은 어떻게 나누고 싶어?',
        choices: [
          {
            choiceIntentId: 'family_say_worry',
            text: '걱정된다고 말할래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['verbal_expression', 'family_support_preference'],
            responseLines: ['걱정된다고 말해도 괜찮아.', '말하면 마음이 조금 가벼워질 수 있어.'],
            endingLines: ['그 마음은 천천히 전해도 돼.', '다음에 또 이야기하자.'],
          },
          {
            choiceIntentId: 'family_tell_teacher',
            text: '선생님께 말할래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['medical_support_preference', 'support_seeking'],
            responseLines: ['선생님에게 말하면 같이 도와줄 수 있어.'],
            endingLines: ['혼자만 걱정하지 않아도 돼.', '필요하면 다시 와.'],
          },
          {
            choiceIntentId: 'family_show_drawing',
            text: '그림으로 보여줄래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: ['prefers_nonverbal_expression'],
            protectiveFactors: ['creative_expression', 'alternative_expression'],
            responseLines: ['그림으로 보여줘도 괜찮아.', '말보다 편할 때가 있어.'],
            endingLines: ['네 방식대로 전해도 괜찮아.', '편할 때 또 와.'],
          },
        ],
      },
    },
  },
  {
    scriptId: 'peer_connection_support',
    title: '친구와 학교 생각',
    domain: 'peer',
    weight: 2,
    contextLine: '친구나 학교 생각이 날 때가 있지.',
    fallbackEndingLine: '언제든 놀러 와.',
    startNodeId: 'peer_01',
    nodes: {
      peer_01: {
        nodeId: 'peer_01',
        questionText: '친구나 학교 생각이 나?',
        choices: [
          {
            choiceIntentId: 'peer_miss_friends',
            text: '친구가 보고 싶어요',
            nextNodeId: 'peer_friend_02',
            intensity: 2,
            concernFlags: ['peer_separation', 'loneliness'],
            protectiveFactors: ['relationship_named'],
            responseLines: ['친구가 보고 싶은 마음이 들 수 있어.', '친구에게 뭐라고 해보고 싶어?'],
          },
          {
            choiceIntentId: 'peer_curious_school',
            text: '학교 소식이 궁금해요',
            nextNodeId: 'peer_school_02',
            intensity: 1,
            concernFlags: ['school_connection'],
            protectiveFactors: ['social_connection', 'information_seeking'],
            responseLines: ['학교에서 뭐 하는지 궁금할 수 있어.', '천천히 들어도 괜찮아.'],
          },
          {
            choiceIntentId: 'peer_okay_now',
            text: '지금은 괜찮아요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['positive_social_state'],
            responseLines: ['지금은 괜찮구나.', '필요하면 나중에 다시 이야기해도 돼.'],
            endingLines: ['생각나면 다시 이야기해도 돼.', '언제든 놀러 와.'],
          },
        ],
      },
      peer_friend_02: {
        nodeId: 'peer_friend_02',
        questionText: '친구에게 뭘 보내고 싶어?',
        choices: [
          {
            choiceIntentId: 'peer_short_hi',
            text: '짧게 인사할래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['verbal_expression', 'social_connection'],
            responseLines: ['짧게 인사해도 마음이 전해질 수 있어.'],
            endingLines: ['다음에 또 이야기해도 돼.', '언제든 나한테 놀러 와.'],
          },
          {
            choiceIntentId: 'peer_send_drawing',
            text: '그림을 보낼래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: ['prefers_nonverbal_expression'],
            protectiveFactors: ['creative_expression', 'alternative_expression'],
            responseLines: ['그림은 말보다 편하게 전해질 때가 있어.'],
            endingLines: ['네 방식대로 전해도 괜찮아.', '또 놀러 와.'],
          },
          {
            choiceIntentId: 'peer_talk_later',
            text: '나중에 말할래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 1,
            concernFlags: ['hesitation_to_share'],
            protectiveFactors: ['sets_boundary'],
            responseLines: ['지금 바로 말하지 않아도 괜찮아.'],
            endingLines: ['나중에 말해도 괜찮아.', '나는 여기 있을게.'],
          },
        ],
      },
      peer_school_02: {
        nodeId: 'peer_school_02',
        questionText: '학교 이야기는 어떻게 듣고 싶어?',
        choices: [
          {
            choiceIntentId: 'school_ask_family',
            text: '가족에게 물어볼래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['family_support_preference', 'information_seeking'],
            responseLines: ['가족에게 물어보면 편하게 들을 수 있어.'],
            endingLines: ['궁금한 건 천천히 물어봐도 돼.', '다음에 또 이야기하자.'],
          },
          {
            choiceIntentId: 'school_ask_friend',
            text: '친구에게 물어볼래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['social_connection', 'information_seeking'],
            responseLines: ['친구에게 짧게 물어봐도 괜찮아.'],
            endingLines: ['짧게 물어봐도 괜찮아.', '편할 때 또 와.'],
          },
          {
            choiceIntentId: 'school_later',
            text: '나중에 들을래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 1,
            concernFlags: ['hesitation_to_share'],
            protectiveFactors: ['sets_boundary'],
            responseLines: ['지금 바로 듣지 않아도 괜찮아.'],
            endingLines: ['나중에 들어도 괜찮아.', '나는 여기 있을게.'],
          },
        ],
      },
    },
  },
  {
    scriptId: 'emotion_expression_support',
    title: '마음 표현 방법',
    domain: 'expression',
    weight: 2,
    contextLine: '말로 하기 어려운 날도 있어.',
    fallbackEndingLine: '언제든 다시 놀러 와.',
    startNodeId: 'expression_01',
    nodes: {
      expression_01: {
        nodeId: 'expression_01',
        questionText: '말하기 어려우면 어떻게 할까?',
        choices: [
          {
            choiceIntentId: 'expression_words',
            text: '짧게 말할래요',
            nextNodeId: 'expression_words_02',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['verbal_expression', 'support_seeking'],
            responseLines: ['좋아. 짧게 말해도 충분해.', '누구에게 말해보고 싶어?'],
          },
          {
            choiceIntentId: 'expression_drawing',
            text: '그림으로 할래요',
            nextNodeId: 'expression_drawing_02',
            intensity: 0,
            concernFlags: ['prefers_nonverbal_expression'],
            protectiveFactors: ['creative_expression', 'alternative_expression'],
            responseLines: ['좋아. 그림으로 해도 괜찮아.', '말보다 편할 때가 있지.'],
          },
          {
            choiceIntentId: 'expression_not_sure',
            text: '아직 모르겠어요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 2,
            concernFlags: ['uncertainty'],
            protectiveFactors: ['uncertainty_named'],
            responseLines: ['아직 몰라도 괜찮아.', '천천히 골라도 돼.'],
            endingLines: ['네 방식대로 해도 괜찮아.', '언제든 다시 놀러 와.'],
          },
        ],
      },
      expression_words_02: {
        nodeId: 'expression_words_02',
        questionText: '누구에게 말해볼까?',
        choices: [
          {
            choiceIntentId: 'expression_family',
            text: '가족에게요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['family_support_preference', 'support_seeking'],
            responseLines: ['가족에게 말하면 마음이 조금 가벼워질 수 있어.'],
            endingLines: ['네 방식대로 해도 괜찮아.', '다음에 또 와.'],
          },
          {
            choiceIntentId: 'expression_teacher',
            text: '선생님에게요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['medical_support_preference', 'support_seeking'],
            responseLines: ['선생님도 네 마음을 들어줄 수 있어.'],
            endingLines: ['말하고 싶을 때 말해도 돼.', '나는 여기 있을게.'],
          },
          {
            choiceIntentId: 'expression_private',
            text: '아직은 나만 알고 싶어요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 1,
            concernFlags: ['hesitation_to_share'],
            protectiveFactors: ['sets_boundary'],
            responseLines: ['지금은 혼자 알고 있어도 괜찮아.', '말하고 싶을 때 다시 꺼내도 돼.'],
            endingLines: ['천천히 해도 괜찮아.', '편할 때 다시 와.'],
          },
        ],
      },
      expression_drawing_02: {
        nodeId: 'expression_drawing_02',
        questionText: '그림을 누구에게 보여줄까?',
        choices: [
          {
            choiceIntentId: 'drawing_family',
            text: '가족에게요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['family_support_preference', 'creative_expression'],
            responseLines: ['가족에게 보여주면 마음이 조금 가벼워질 수 있어.'],
            endingLines: ['네 방식대로 해도 괜찮아.', '다음에 또 와.'],
          },
          {
            choiceIntentId: 'drawing_teacher',
            text: '선생님에게요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['medical_support_preference', 'creative_expression'],
            responseLines: ['선생님도 네 그림을 봐줄 수 있어.'],
            endingLines: ['말하고 싶을 때 말해도 돼.', '나는 여기 있을게.'],
          },
          {
            choiceIntentId: 'drawing_private',
            text: '아직은 나만 볼래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 1,
            concernFlags: ['hesitation_to_share'],
            protectiveFactors: ['sets_boundary'],
            responseLines: [
              '좋아. 아직은 혼자 봐도 괜찮아.',
              '나중에 보여주고 싶을 때 보여줘도 돼.',
            ],
            endingLines: ['천천히 해도 괜찮아.', '편할 때 다시 와.'],
          },
        ],
      },
    },
  },
  {
    scriptId: 'upset_anger_support',
    title: '속상함과 화',
    domain: 'anger',
    weight: 1,
    contextLine: '기분이 복잡한 날도 있지.',
    fallbackEndingLine: '필요하면 다시 와.',
    startNodeId: 'anger_01',
    nodes: {
      anger_01: {
        nodeId: 'anger_01',
        questionText: '속상할 땐 어떻게 하고 싶어?',
        choices: [
          {
            choiceIntentId: 'anger_pause',
            text: '잠깐 멈출래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 1,
            concernFlags: ['anger_or_frustration'],
            protectiveFactors: ['pause_coping', 'self_regulation'],
            responseLines: ['좋아. 잠깐 멈추는 것도 방법이야.', '천천히 다시 해도 괜찮아.'],
            endingLines: ['잠깐 쉬어가도 괜찮아.', '다음에 또 놀러 와.'],
          },
          {
            choiceIntentId: 'anger_say_upset',
            text: '속상하다고 말할래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 1,
            concernFlags: ['anger_or_frustration'],
            protectiveFactors: ['emotion_named', 'verbal_expression'],
            responseLines: ['속상하다고 말해도 괜찮아.', '말하면 조금 덜 답답할 수 있어.'],
            endingLines: ['천천히 말해도 괜찮아.', '나는 여기 있을게.'],
          },
          {
            choiceIntentId: 'anger_call_help',
            text: '도와달라고 말할래요',
            nextNodeId: null,
            endAfterSelect: true,
            intensity: 1,
            concernFlags: ['anger_or_frustration'],
            protectiveFactors: ['support_seeking', 'self_regulation'],
            responseLines: [
              '혼자 하기 어려울 땐 도와달라고 말해도 괜찮아.',
              '도움을 받는 것도 좋은 방법이야.',
            ],
            endingLines: ['혼자 하지 않아도 돼.', '필요하면 다시 와.'],
          },
        ],
      },
    },
  },
]

export function pickRandomCounselingScript(scripts: CounselingScript[]) {
  if (scripts.length === 0) {
    throw new Error('No counseling scripts available')
  }

  const today = new Date().toISOString().slice(0, 10)
  const key = `recent_shared_counseling_script_${today}`
  const recentScriptId = localStorage.getItem(key)

  const candidates =
    scripts.length > 1 ? scripts.filter(script => script.scriptId !== recentScriptId) : scripts
  const pool = candidates.length > 0 ? candidates : scripts
  const totalWeight = pool.reduce((sum, script) => sum + (script.weight ?? 1), 0)
  let random = Math.random() * totalWeight

  for (const script of pool) {
    random -= script.weight ?? 1
    if (random <= 0) {
      localStorage.setItem(key, script.scriptId)
      return script
    }
  }

  localStorage.setItem(key, pool[0].scriptId)
  return pool[0]
}
