import { applyActivityAwareEndingTypes } from './activityAwareEnding'
import type { CounselingNode, CounselingScript } from './types'

const nodes: Record<string, CounselingNode> = {
  entry_01: {
    nodeId: 'entry_01',
    questionText: '오늘은 어떻게 지내고 싶어?',
    choices: [
      {
        choiceIntentId: 'entry_rest',
        text: '쉬면서 있고 싶어요',
        nextNodeId: 'rest_01',
        intensity: 1,
        concernFlags: ['needs_rest'],
        protectiveFactors: ['sets_boundary', 'rest_need_named'],
        responseKey: 'entry_rest',
        fallbackResponseLines: ['좋아. 쉬고 싶은 날도 있지.', '그럼 어떻게 쉬고 싶은지 골라보자.'],
      },
      {
        choiceIntentId: 'entry_activity',
        text: '뭔가 해보고 싶어요',
        nextNodeId: 'activity_01',
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['agency_coping', 'positive_activity_interest'],
        responseKey: 'entry_activity',
        fallbackResponseLines: ['좋아. 가볍게 시작해도 괜찮아.', '오늘은 어떤 게 끌려?'],
      },
      {
        choiceIntentId: 'entry_talk',
        text: '잠깐 얘기하고 싶어요',
        nextNodeId: 'talk_topic_01',
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['support_seeking', 'verbal_expression'],
        responseKey: 'entry_talk',
        fallbackResponseLines: ['좋아. 길게 말하지 않아도 돼.', '편한 얘기부터 골라보자.'],
      },
    ],
  },

  rest_01: {
    nodeId: 'rest_01',
    questionText: '어떻게 쉬고 싶어?',
    choices: [
      {
        choiceIntentId: 'rest_quiet',
        text: '조용히 있을래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['needs_rest'],
        protectiveFactors: ['sets_boundary'],
        responseKey: 'rest_quiet',
        fallbackResponseLines: ['조용히 있어도 괜찮아.', '말하지 않고 쉬어도 돼.'],
        endingType: 'REST_THEN_ACTIVITY',
      },
      {
        choiceIntentId: 'rest_close_eyes',
        text: '눈을 감고 있을래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['fatigue_present'],
        protectiveFactors: ['self_care_action', 'rest_need_named'],
        responseKey: 'rest_eyes',
        fallbackResponseLines: ['눈을 잠깐 감는 것도 쉬는 방법이야.', '몸이 조금 편해질 수 있어.'],
        endingType: 'REST_ONLY',
      },
      {
        choiceIntentId: 'rest_near_family',
        text: '가족 옆에 있을래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['family_support_preference', 'support_need_named'],
        responseKey: 'rest_family',
        fallbackResponseLines: ['편한 사람 옆에 있으면 마음도 쉬기 쉬워.', '그렇게 쉬어도 괜찮아.'],
        endingType: 'REST_ONLY',
      },
    ],
  },

  activity_01: {
    nodeId: 'activity_01',
    questionText: '가볍게 뭘 해볼까?',
    choices: [
      {
        choiceIntentId: 'activity_music',
        text: '음악을 들어볼래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['positive_activity_interest', 'music_interest'],
        responseKey: 'activity_music',
        fallbackResponseLines: ['좋아. 듣는 것부터 시작해도 돼.', '짧게 들어도 충분해.'],
        endingType: 'GO_LIGHT_ACTIVITY',
      },
      {
        choiceIntentId: 'activity_art',
        text: '그림을 그려볼래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['creative_expression', 'positive_activity_interest'],
        responseKey: 'activity_art',
        fallbackResponseLines: ['좋아. 그림은 말보다 편할 때가 있어.', '생각나는 것만 그려도 돼.'],
        endingType: 'EXPRESS_WITH_DRAWING',
      },
      {
        choiceIntentId: 'activity_move',
        text: '조금 움직여볼래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['movement_interest', 'agency_coping'],
        responseKey: 'activity_move',
        fallbackResponseLines: ['좋아. 아주 조금만 움직여도 괜찮아.', '힘들면 멈춰도 돼.'],
        endingType: 'GO_LIGHT_ACTIVITY',
      },
    ],
  },

  talk_topic_01: {
    nodeId: 'talk_topic_01',
    questionText: '무슨 얘기가 좋을까?',
    choices: [
      {
        choiceIntentId: 'talk_body',
        text: '몸 얘기',
        nextNodeId: 'body_01',
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['body_checkin_interest'],
        responseKey: 'talk_body',
        fallbackResponseLines: ['좋아. 몸이 어떤지 잠깐만 살펴보자.'],
      },
      {
        choiceIntentId: 'talk_peer',
        text: '친구나 학교 얘기',
        nextNodeId: 'peer_01',
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['social_connection_interest'],
        responseKey: 'talk_peer',
        fallbackResponseLines: ['좋아. 친구나 학교 생각이 나는 날도 있지.'],
      },
      {
        choiceIntentId: 'talk_worry',
        text: '걱정되는 얘기',
        nextNodeId: 'worry_01',
        intensity: 1,
        concernFlags: ['worry_present'],
        protectiveFactors: ['emotion_named', 'support_seeking'],
        responseKey: 'talk_worry',
        fallbackResponseLines: [
          '좋아. 걱정되는 게 있으면 조금만 말해도 돼.',
          '말하기 싫은 건 괜찮다고 해도 돼.',
        ],
      },
    ],
  },

  body_01: {
    nodeId: 'body_01',
    questionText: '지금 몸은 어때?',
    choices: [
      {
        choiceIntentId: 'body_okay_now',
        text: '괜찮아요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['positive_body_state'],
        responseKey: 'body_okay',
        fallbackResponseLines: ['좋아. 지금은 괜찮구나.', '그래도 불편해지면 바로 말해도 돼.'],
        endingType: 'GO_LIGHT_ACTIVITY',
      },
      {
        choiceIntentId: 'body_tired_easy',
        text: '금방 힘이 빠져요',
        nextNodeId: 'body_rest_02',
        intensity: 2,
        concernFlags: ['fatigue_present', 'body_discomfort'],
        protectiveFactors: ['body_state_named'],
        responseKey: 'body_tired',
        fallbackResponseLines: ['그럴 때 있지.', '힘이 빠지면 잠깐 쉬어도 돼.'],
      },
      {
        choiceIntentId: 'body_pain_worry',
        text: '아픈 게 걱정돼요',
        nextNodeId: 'body_pain_02',
        intensity: 3,
        concernFlags: ['pain_concern', 'procedure_fear'],
        protectiveFactors: ['can_name_fear'],
        responseKey: 'body_pain_worry',
        fallbackResponseLines: [
          '아픈 게 걱정되면 혼자 참지 않아도 돼.',
          '어떻게 알려줄지 같이 골라보자.',
        ],
      },
    ],
  },

  body_rest_02: {
    nodeId: 'body_rest_02',
    questionText: '그럴 땐 어떻게 쉬고 싶어?',
    choices: [
      {
        choiceIntentId: 'body_rest_quiet',
        text: '조용히 있고 싶어요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['needs_rest'],
        protectiveFactors: ['sets_boundary'],
        responseKey: 'body_rest_quiet',
        fallbackResponseLines: ['조용히 있어도 괜찮아.', '말하지 않고 쉬어도 돼.'],
        endingType: 'REST_THEN_ACTIVITY',
      },
      {
        choiceIntentId: 'body_family_near',
        text: '가족 옆에 있고 싶어요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['family_support_preference', 'support_need_named'],
        responseKey: 'body_family_near',
        fallbackResponseLines: [
          '편한 사람 옆에 있으면 조금 나아질 수 있어.',
          '그렇게 쉬어도 괜찮아.',
        ],
        endingType: 'REST_ONLY',
      },
      {
        choiceIntentId: 'body_tell_adult',
        text: '가까운 사람에게 말할래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['support_seeking', 'adult_support_preference'],
        responseKey: 'body_tell_adult',
        fallbackResponseLines: [
          '좋아. 가까운 사람에게 말하면 같이 도와줄 수 있어.',
          '혼자 참고 있지 않아도 돼.',
        ],
        endingType: 'ASK_ADULT_FIRST',
      },
    ],
  },

  body_pain_02: {
    nodeId: 'body_pain_02',
    questionText: '아플 때는 어떻게 알려줄까?',
    choices: [
      {
        choiceIntentId: 'pain_tell_teacher',
        text: '선생님께 말할래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['medical_support_preference', 'support_seeking'],
        responseKey: 'pain_tell_teacher',
        fallbackResponseLines: ['좋아. 선생님께 말하면 도와줄 수 있어.', '작은 아픔도 말해도 돼.'],
        endingType: 'ASK_MEDICAL_FIRST',
      },
      {
        choiceIntentId: 'pain_point_place',
        text: '아픈 곳을 가리킬래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['prefers_nonverbal_expression'],
        protectiveFactors: ['alternative_expression', 'body_state_named'],
        responseKey: 'pain_point_place',
        fallbackResponseLines: ['손으로 알려줘도 괜찮아.', '말이 안 나올 때는 그 방법도 좋아.'],
        endingType: 'ASK_HELP_FIRST',
      },
      {
        choiceIntentId: 'pain_hold_hand',
        text: '손을 잡아줬으면 해요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['needs_comfort'],
        protectiveFactors: ['comfort_preference_named', 'support_need_named'],
        responseKey: 'pain_hold_hand',
        fallbackResponseLines: ['손을 잡아달라고 해도 괜찮아.', '그게 조금 든든할 때도 있어.'],
        endingType: 'REST_ONLY',
      },
    ],
  },

  peer_01: {
    nodeId: 'peer_01',
    questionText: '친구나 학교 생각이 나?',
    choices: [
      {
        choiceIntentId: 'peer_miss_friends',
        text: '친구가 보고 싶어요',
        nextNodeId: 'peer_friend_02',
        intensity: 2,
        concernFlags: ['peer_separation', 'loneliness'],
        protectiveFactors: ['relationship_named'],
        responseKey: 'peer_miss',
        fallbackResponseLines: ['친구가 보고 싶은 마음이 들 수 있어.', '길게 말하지 않아도 돼.'],
      },
      {
        choiceIntentId: 'peer_curious_school',
        text: '학교 소식이 궁금해요',
        nextNodeId: 'peer_school_02',
        intensity: 1,
        concernFlags: ['school_connection'],
        protectiveFactors: ['social_connection', 'information_seeking'],
        responseKey: 'school_curious',
        fallbackResponseLines: ['학교에서 뭐 하는지 궁금할 수 있어.', '천천히 들어도 괜찮아.'],
      },
      {
        choiceIntentId: 'peer_okay_now',
        text: '지금은 괜찮아요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['positive_social_state'],
        fallbackResponseLines: ['좋아. 지금은 괜찮구나.', '필요하면 나중에 다시 이야기해도 돼.'],
        endingType: 'GO_LIGHT_ACTIVITY',
      },
    ],
  },

  peer_friend_02: {
    nodeId: 'peer_friend_02',
    questionText: '친구 생각이 날 땐 뭐가 좋을까?',
    choices: [
      {
        choiceIntentId: 'peer_short_hi',
        text: '짧게 인사하고 싶어요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['verbal_expression', 'social_connection'],
        responseKey: 'peer_miss',
        fallbackResponseLines: ['짧게 인사해도 마음이 전해질 수 있어.'],
        endingType: 'SOCIAL_CONNECT',
      },
      {
        choiceIntentId: 'peer_draw',
        text: '그림을 그리고 싶어요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: ['prefers_nonverbal_expression'],
        protectiveFactors: ['creative_expression', 'alternative_expression'],
        responseKey: 'peer_draw',
        fallbackResponseLines: ['그림으로 표현해도 좋아.', '말보다 쉬울 때가 있지.'],
        endingType: 'EXPRESS_WITH_DRAWING',
      },
      {
        choiceIntentId: 'peer_talk_later',
        text: '나중에 얘기할래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['hesitation_to_share'],
        protectiveFactors: ['sets_boundary'],
        responseKey: 'peer_later',
        fallbackResponseLines: ['지금 바로 말하지 않아도 괜찮아.', '나중에 해도 돼.'],
        endingType: 'PRIVATE_OKAY',
      },
    ],
  },

  peer_school_02: {
    nodeId: 'peer_school_02',
    questionText: '학교 이야기는 어떻게 듣고 싶어?',
    choices: [
      {
        choiceIntentId: 'school_ask_family',
        text: '가족에게 물어볼래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['family_support_preference', 'information_seeking'],
        responseKey: 'school_ask_family',
        fallbackResponseLines: ['가족에게 물어보면 편하게 들을 수 있어.'],
        endingType: 'ASK_HELP_FIRST',
      },
      {
        choiceIntentId: 'school_ask_friend',
        text: '친구에게 물어볼래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['social_connection', 'information_seeking'],
        responseKey: 'school_ask_friend',
        fallbackResponseLines: ['친구에게 짧게 물어봐도 괜찮아.'],
        endingType: 'SOCIAL_CONNECT',
      },
      {
        choiceIntentId: 'school_later',
        text: '나중에 들을래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['hesitation_to_share'],
        protectiveFactors: ['sets_boundary'],
        responseKey: 'school_later',
        fallbackResponseLines: ['지금 바로 듣지 않아도 괜찮아.'],
        endingType: 'PRIVATE_OKAY',
      },
    ],
  },

  worry_01: {
    nodeId: 'worry_01',
    questionText: '어떤 게 제일 신경 쓰여?',
    choices: [
      {
        choiceIntentId: 'worry_hospital',
        text: '병원 일이 걱정돼요',
        nextNodeId: 'hospital_02',
        intensity: 2,
        concernFlags: ['hospital_worry', 'worry_present'],
        protectiveFactors: ['emotion_named'],
        responseKey: 'worry_hospital',
        fallbackResponseLines: ['병원 일이 신경 쓰일 수 있어.', '말하기 싫으면 괜찮다고 해도 돼.'],
      },
      {
        choiceIntentId: 'worry_family',
        text: '가족이 걱정돼요',
        nextNodeId: 'family_worry_02',
        intensity: 3,
        concernFlags: ['family_worry', 'parent_concern'],
        protectiveFactors: ['relationship_named', 'empathy'],
        responseKey: 'worry_family',
        fallbackResponseLines: ['가족이 걱정될 때도 있지.', '혼자만 걱정하지 않아도 돼.'],
      },
      {
        choiceIntentId: 'worry_upset',
        text: '속상한 일이 있어요',
        nextNodeId: 'anger_02',
        intensity: 2,
        concernFlags: ['anger_or_frustration', 'distress_present'],
        protectiveFactors: ['emotion_named'],
        responseKey: 'worry_upset',
        fallbackResponseLines: ['속상한 일이 있었구나.', '지금 바로 다 말하지 않아도 돼.'],
      },
    ],
  },

  hospital_02: {
    nodeId: 'hospital_02',
    questionText: '어떤 게 조금 걸려?',
    choices: [
      {
        choiceIntentId: 'hospital_injection',
        text: '주사가 걱정돼요',
        nextNodeId: 'hospital_support_03',
        intensity: 3,
        concernFlags: ['procedure_fear', 'pain_concern'],
        protectiveFactors: ['can_name_fear'],
        responseKey: 'hospital_injection',
        fallbackResponseLines: ['그럴 수 있어.', '주사 생각만 해도 걱정될 때가 있지.'],
      },
      {
        choiceIntentId: 'hospital_unknown',
        text: '어떻게 하는지 모르겠어요',
        nextNodeId: 'hospital_question_03',
        intensity: 2,
        concernFlags: ['uncertainty', 'information_need'],
        protectiveFactors: ['uncertainty_named'],
        responseKey: 'hospital_unknown',
        fallbackResponseLines: ['모르면 더 걱정될 수 있어.', '물어보는 건 괜찮은 일이야.'],
      },
      {
        choiceIntentId: 'hospital_okay',
        text: '지금은 괜찮아요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['positive_mood'],
        responseKey: 'hospital_okay',
        fallbackResponseLines: ['좋아. 지금은 괜찮구나.', '필요하면 나중에 다시 말해도 돼.'],
        endingType: 'GO_LIGHT_ACTIVITY',
      },
    ],
  },

  hospital_support_03: {
    nodeId: 'hospital_support_03',
    questionText: '그럴 땐 뭐가 조금 나을까?',
    choices: [
      {
        choiceIntentId: 'hospital_family_near',
        text: '가족이 옆에 있으면 좋아요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['family_support_preference', 'support_need_named'],
        responseKey: 'hospital_family_near',
        fallbackResponseLines: ['가족이 옆에 있으면 조금 든든할 수 있어.', '그렇게 말해도 괜찮아.'],
        endingType: 'REST_ONLY',
      },
      {
        choiceIntentId: 'hospital_teacher_explain',
        text: '선생님이 설명해주면 좋아요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['information_seeking', 'medical_support_preference'],
        responseKey: 'hospital_teacher_explain',
        fallbackResponseLines: ['설명을 들으면 덜 낯설 수 있어.', '모르는 건 물어봐도 돼.'],
        endingType: 'ASK_MEDICAL_FIRST',
      },
      {
        choiceIntentId: 'hospital_hold_hand',
        text: '손을 잡아줬으면 해요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['needs_comfort'],
        protectiveFactors: ['comfort_preference_named', 'support_need_named'],
        responseKey: 'hospital_hold_hand',
        fallbackResponseLines: ['손을 잡아달라고 말해도 괜찮아.', '혼자 견디지 않아도 돼.'],
        endingType: 'REST_ONLY',
      },
    ],
  },

  hospital_question_03: {
    nodeId: 'hospital_question_03',
    questionText: '누구에게 물어보면 좋을까?',
    choices: [
      {
        choiceIntentId: 'hospital_ask_teacher',
        text: '선생님께 물어볼래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['information_seeking', 'medical_support_preference'],
        responseKey: 'hospital_ask_teacher',
        fallbackResponseLines: ['좋아. 선생님께 물어보면 차근차근 알려줄 수 있어.'],
        endingType: 'ASK_MEDICAL_FIRST',
      },
      {
        choiceIntentId: 'hospital_ask_family',
        text: '가족이랑 물어볼래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['family_support_preference', 'information_seeking'],
        responseKey: 'hospital_ask_family',
        fallbackResponseLines: ['가족이랑 같이 물어보면 더 든든할 수 있어.'],
        endingType: 'ASK_HELP_FIRST',
      },
      {
        choiceIntentId: 'hospital_draw_question',
        text: '그림으로 물어볼래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: ['prefers_nonverbal_expression'],
        protectiveFactors: ['alternative_expression', 'creative_expression'],
        responseKey: 'hospital_draw_question',
        fallbackResponseLines: ['그림으로 물어봐도 괜찮아.', '말보다 쉬울 때가 있지.'],
        endingType: 'EXPRESS_WITH_DRAWING',
      },
    ],
  },

  family_worry_02: {
    nodeId: 'family_worry_02',
    questionText: '그럴 땐 누구에게 말하면 좋을까?',
    choices: [
      {
        choiceIntentId: 'family_say_worry',
        text: '가족에게 말할래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['verbal_expression', 'family_support_preference'],
        responseKey: 'family_say_worry',
        fallbackResponseLines: ['좋아. 걱정된다고 말해도 괜찮아.', '말하면 조금 가벼워질 수 있어.'],
        endingType: 'ASK_HELP_FIRST',
      },
      {
        choiceIntentId: 'family_tell_teacher',
        text: '선생님께 말할래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['medical_support_preference', 'support_seeking'],
        responseKey: 'family_tell_teacher',
        fallbackResponseLines: [
          '선생님께 말하면 같이 도와줄 수 있어.',
          '혼자만 들고 있지 않아도 돼.',
        ],
        endingType: 'ASK_MEDICAL_FIRST',
      },
      {
        choiceIntentId: 'family_show_drawing',
        text: '그림으로 보여줄래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: ['prefers_nonverbal_expression'],
        protectiveFactors: ['creative_expression', 'alternative_expression'],
        responseKey: 'family_show_drawing',
        fallbackResponseLines: ['그림으로 보여줘도 괜찮아.', '네 방식대로 전해도 돼.'],
        endingType: 'EXPRESS_WITH_DRAWING',
      },
    ],
  },

  anger_02: {
    nodeId: 'anger_02',
    questionText: '그럴 땐 어떻게 하고 싶어?',
    choices: [
      {
        choiceIntentId: 'anger_pause',
        text: '잠깐 멈출래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['anger_or_frustration'],
        protectiveFactors: ['pause_coping', 'self_regulation'],
        responseKey: 'anger_pause',
        fallbackResponseLines: ['좋아. 잠깐 멈추는 것도 방법이야.', '천천히 다시 해도 돼.'],
        endingType: 'CALM_DOWN',
      },
      {
        choiceIntentId: 'anger_say_upset',
        text: '속상하다고 말할래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['anger_or_frustration'],
        protectiveFactors: ['emotion_named', 'verbal_expression'],
        responseKey: 'anger_say_upset',
        fallbackResponseLines: ['속상하다고 말해도 괜찮아.', '말하면 조금 덜 답답할 수 있어.'],
        endingType: 'ASK_HELP_FIRST',
      },
      {
        choiceIntentId: 'anger_call_help',
        text: '도와달라고 말할래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['anger_or_frustration'],
        protectiveFactors: ['support_seeking', 'self_regulation'],
        responseKey: 'anger_call_help',
        fallbackResponseLines: [
          '혼자 하기 어려울 땐 도와달라고 말해도 괜찮아.',
          '도움을 받는 것도 좋은 방법이야.',
        ],
        endingType: 'ASK_HELP_FIRST',
      },
    ],
  },
}

export const VILLAGER_COUNSELING_SCRIPT: CounselingScript = {
  scriptId: 'villager_common_entry',
  title: '마을 주민 공통 대화',
  startNodeId: 'entry_01',
  nodes,
}

export const SHARED_COUNSELING_SCRIPTS: CounselingScript[] = applyActivityAwareEndingTypes([
  VILLAGER_COUNSELING_SCRIPT,
])

export function pickRandomCounselingScript(scripts: CounselingScript[]) {
  if (scripts.length === 0) {
    throw new Error('No counseling scripts available')
  }

  return scripts[0]
}
