import type { CounselingNode, CounselingScript } from './types'
import { applyActivityAwareEndingTypes } from './activityAwareEnding'

const ENTRY_COUNSELING_NODES: Record<string, CounselingNode> = {
  entry_01: {
    nodeId: 'entry_01',
    questionText: '오늘은 뭐가 좋을까?',
    choices: [
      {
        choiceIntentId: 'entry_rest',
        text: '쉬고 싶어요',
        nextNodeId: 'rest_01',
        intensity: 1,
        concernFlags: ['needs_rest'],
        protectiveFactors: ['sets_boundary', 'rest_need_named'],
        responseLines: ['좋아. 쉬고 싶은 날도 있지.', '그럼 어떻게 쉬고 싶은지 골라보자.'],
      },
      {
        choiceIntentId: 'entry_activity',
        text: '뭔가 해보고 싶어요',
        nextNodeId: 'activity_01',
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['agency_coping', 'positive_activity_interest'],
        responseLines: ['좋아. 가볍게 시작해도 괜찮아.', '오늘은 어떤 게 끌려?'],
      },
      {
        choiceIntentId: 'entry_talk',
        text: '얘기하고 싶어요',
        nextNodeId: 'talk_topic_01',
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['support_seeking', 'verbal_expression'],
        responseLines: ['좋아. 길게 말하지 않아도 돼.', '편한 얘기부터 골라보자.'],
      },
    ],
  },
  rest_01: {
    nodeId: 'rest_01',
    questionText: '어떻게 쉬고 싶어?',
    choices: [
      {
        choiceIntentId: 'rest_quiet',
        text: '조용히 있을래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['needs_rest'],
        protectiveFactors: ['sets_boundary'],
        responseLines: ['조용히 있어도 괜찮아.', '말하지 않고 쉬어도 돼.'],
        activityEndingLines: {
          pending: ['먼저 조금 쉬어가자.', '괜찮아지면 가벼운 활동 하나만 해보자.'],
          completed: ['오늘은 이 정도면 충분해.', '천천히 쉬어가자.'],
        },
      },
      {
        choiceIntentId: 'rest_close_eyes',
        text: '눈을 감고 있을래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['fatigue_present'],
        protectiveFactors: ['self_care_action', 'rest_need_named'],
        responseLines: ['눈을 잠깐 감는 것도 쉬는 방법이야.', '몸이 조금 편해질 수 있어.'],
        endingLines: ['지금은 잠깐 쉬어도 괜찮아.', '활동은 천천히 해도 돼.'],
      },
      {
        choiceIntentId: 'rest_near_family',
        text: '가족 옆에 있을래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['family_support_preference', 'support_need_named'],
        responseLines: ['편한 사람 옆에 있으면 마음도 쉬기 쉬워.', '그렇게 쉬어도 괜찮아.'],
        endingLines: ['편한 곳에서 쉬어가자.', '오늘은 네 속도대로 가도 괜찮아.'],
      },
    ],
  },
  activity_01: {
    nodeId: 'activity_01',
    questionText: '가볍게 뭘 해볼까?',
    choices: [
      {
        choiceIntentId: 'activity_music',
        text: '음악을 들어볼래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['positive_activity_interest', 'music_coping'],
        responseLines: ['좋아. 듣는 것부터 시작해도 돼.', '짧게 들어도 충분해.'],
        endingLines: ['그럼 음악 활동부터 가볍게 해보자.'],
      },
      {
        choiceIntentId: 'activity_drawing',
        text: '그림을 그려볼래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['creative_expression', 'positive_activity_interest'],
        responseLines: ['좋아. 그림은 말보다 편할 때가 있어.', '생각나는 것만 그려도 돼.'],
        endingLines: ['그럼 미술 활동으로 남겨봐도 좋아.'],
      },
      {
        choiceIntentId: 'activity_move',
        text: '조금 움직여볼래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['movement_coping', 'positive_activity_interest'],
        responseLines: ['좋아. 아주 조금만 움직여도 괜찮아.', '힘들면 멈춰도 돼.'],
        endingLines: ['그럼 가벼운 활동부터 해보자.', '천천히 따라가도 괜찮아.'],
      },
    ],
  },
  talk_topic_01: {
    nodeId: 'talk_topic_01',
    questionText: '무슨 얘기가 좋을까?',
    choices: [
      {
        choiceIntentId: 'talk_body',
        text: '몸 얘기',
        nextNodeId: 'body_01',
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['body_state_named'],
        responseLines: ['좋아. 몸 얘기부터 해보자.', '편한 만큼만 말해도 돼.'],
      },
      {
        choiceIntentId: 'talk_peer',
        text: '친구나 학교 얘기',
        nextNodeId: 'peer_01',
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['social_connection'],
        responseLines: ['좋아. 친구나 학교 얘기도 괜찮아.', '생각나는 것부터 골라보자.'],
      },
      {
        choiceIntentId: 'talk_worry',
        text: '걱정되는 얘기',
        nextNodeId: 'worry_01',
        intensity: 1,
        concernFlags: ['worry_present'],
        protectiveFactors: ['support_seeking', 'verbal_expression'],
        responseLines: ['좋아. 걱정되는 얘기도 해도 돼.', '말하기 싫은 건 안 골라도 괜찮아.'],
      },
    ],
  },
  body_01: {
    nodeId: 'body_01',
    questionText: '지금 몸은 어때?',
    choices: [
      {
        choiceIntentId: 'body_okay_now',
        text: '괜찮아요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['positive_body_state'],
        responseLines: ['좋아. 지금은 괜찮구나.', '그래도 불편해지면 바로 말해도 돼.'],
        activityEndingLines: {
          pending: ['괜찮으면 가벼운 활동 하나 해볼까?'],
          completed: ['오늘은 해본 게 있으니까, 잠깐 쉬어도 괜찮아.'],
        },
      },
      {
        choiceIntentId: 'body_tired_easy',
        text: '금방 힘이 빠져요',
        nextNodeId: 'body_rest_02',
        intensity: 2,
        concernFlags: ['fatigue_present', 'body_discomfort'],
        protectiveFactors: ['body_state_named'],
        responseLines: ['그럴 때 있지.', '힘이 빠지면 잠깐 쉬어도 돼.'],
      },
      {
        choiceIntentId: 'body_pain_worry',
        text: '아픈 게 걱정돼요',
        nextNodeId: 'body_pain_02',
        intensity: 3,
        concernFlags: ['pain_concern'],
        protectiveFactors: ['can_name_fear'],
        responseLines: ['아픈 게 걱정되면 혼자 참지 않아도 돼.', '어떻게 알려줄지 같이 골라보자.'],
      },
    ],
  },
  body_rest_02: {
    nodeId: 'body_rest_02',
    questionText: '그럴 땐 어떻게 쉬고 싶어?',
    choices: [
      {
        choiceIntentId: 'body_rest_quiet',
        text: '조용히 있고 싶어요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['needs_rest'],
        protectiveFactors: ['sets_boundary', 'rest_need_named'],
        responseLines: ['조용히 있어도 괜찮아.', '말하지 않고 쉬어도 돼.'],
        endingLines: ['먼저 조금 쉬어가자.', '괜찮아지면 가벼운 활동 하나만 해보자.'],
      },
      {
        choiceIntentId: 'body_family_near',
        text: '가족 옆에 있고 싶어요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['family_support_preference', 'support_need_named'],
        responseLines: ['편한 사람 옆에 있으면 조금 나아질 수 있어.', '그렇게 쉬어도 괜찮아.'],
        endingLines: ['지금은 편한 곳에서 쉬어도 괜찮아.', '활동은 천천히 해도 돼.'],
      },
      {
        choiceIntentId: 'body_tell_close_person',
        text: '가까운 사람에게 말할래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['support_seeking'],
        responseLines: [
          '좋아. 가까운 사람에게 말하면 같이 도와줄 수 있어.',
          '혼자 참고 있지 않아도 돼.',
        ],
        endingLines: ['먼저 가까운 사람에게 알려보자.', '그다음에 천천히 해도 괜찮아.'],
      },
    ],
  },
  body_pain_02: {
    nodeId: 'body_pain_02',
    questionText: '아플 때는 어떻게 알려줄까?',
    choices: [
      {
        choiceIntentId: 'pain_tell_teacher',
        text: '선생님께 말할래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['medical_support_preference', 'support_seeking'],
        responseLines: ['좋아. 선생님께 말하면 도와줄 수 있어.', '작은 아픔도 말해도 돼.'],
        endingLines: ['먼저 선생님께 알려보자.', '활동은 천천히 해도 괜찮아.'],
      },
      {
        choiceIntentId: 'pain_point_place',
        text: '아픈 곳을 가리킬래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['prefers_nonverbal_expression'],
        protectiveFactors: ['alternative_expression', 'body_state_named'],
        responseLines: ['손으로 알려줘도 괜찮아.', '말이 안 나올 때는 그 방법도 좋아.'],
        endingLines: ['네 방식대로 알려줘도 괜찮아.', '혼자 참지 않아도 돼.'],
      },
      {
        choiceIntentId: 'pain_hold_hand',
        text: '손을 잡아줬으면 해요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['needs_comfort'],
        protectiveFactors: ['comfort_preference_named', 'support_need_named'],
        responseLines: ['손을 잡아달라고 해도 괜찮아.', '그게 조금 든든할 때도 있어.'],
        endingLines: ['도움을 받아도 괜찮아.', '지금은 천천히 가자.'],
      },
    ],
  },
  peer_01: {
    nodeId: 'peer_01',
    questionText: '친구나 학교 생각이 나?',
    choices: [
      {
        choiceIntentId: 'peer_miss_friends',
        text: '친구가 보고 싶어요',
        nextNodeId: 'peer_friend_02',
        intensity: 2,
        concernFlags: ['peer_separation', 'loneliness'],
        protectiveFactors: ['relationship_named'],
        responseLines: ['친구가 보고 싶은 마음이 들 수 있어.', '길게 말하지 않아도 돼.'],
      },
      {
        choiceIntentId: 'peer_curious_school',
        text: '학교 소식이 궁금해요',
        nextNodeId: 'peer_school_02',
        intensity: 1,
        concernFlags: ['school_connection'],
        protectiveFactors: ['social_connection', 'information_seeking'],
        responseLines: ['학교에서 뭐 하는지 궁금할 수 있어.', '천천히 들어도 괜찮아.'],
      },
      {
        choiceIntentId: 'peer_okay_now',
        text: '지금은 괜찮아요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['positive_social_state'],
        responseLines: ['좋아. 지금은 괜찮구나.', '필요하면 나중에 다시 이야기해도 돼.'],
        activityEndingLines: {
          pending: ['그럼 가벼운 활동 하나 해볼까?'],
          completed: ['오늘은 이미 해본 게 있으니까, 천천히 쉬어가도 괜찮아.'],
        },
      },
    ],
  },
  peer_friend_02: {
    nodeId: 'peer_friend_02',
    questionText: '친구 생각이 날 땐 뭐가 좋을까?',
    choices: [
      {
        choiceIntentId: 'peer_short_hi',
        text: '짧게 인사하고 싶어요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['verbal_expression', 'social_connection'],
        responseLines: ['짧게 인사해도 마음이 전해질 수 있어.'],
        endingLines: ['짧게 전해도 괜찮아.', '오늘은 천천히 쉬어가자.'],
      },
      {
        choiceIntentId: 'peer_send_drawing',
        text: '그림을 그리고 싶어요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: ['prefers_nonverbal_expression'],
        protectiveFactors: ['creative_expression', 'alternative_expression'],
        responseLines: ['그림으로 표현해도 좋아.', '말보다 쉬울 때가 있지.'],
        endingLines: ['오늘은 그림으로 남겨봐도 좋아.', '네 방식대로 전해도 괜찮아.'],
      },
      {
        choiceIntentId: 'peer_talk_later',
        text: '나중에 얘기할래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['hesitation_to_share'],
        protectiveFactors: ['sets_boundary'],
        responseLines: ['지금 바로 말하지 않아도 괜찮아.', '나중에 해도 돼.'],
        endingLines: ['천천히 해도 괜찮아.', '생각나면 그때 이야기해도 돼.'],
      },
    ],
  },
  peer_school_02: {
    nodeId: 'peer_school_02',
    questionText: '학교 이야기는 어떻게 듣고 싶어?',
    choices: [
      {
        choiceIntentId: 'school_ask_family',
        text: '가족에게 물어볼래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['family_support_preference', 'information_seeking'],
        responseLines: ['가족에게 물어보면 편하게 들을 수 있어.'],
        endingLines: ['궁금한 건 천천히 물어봐도 돼.', '오늘은 네 속도대로 가자.'],
      },
      {
        choiceIntentId: 'school_ask_friend',
        text: '친구에게 물어볼래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['social_connection', 'information_seeking'],
        responseLines: ['친구에게 짧게 물어봐도 괜찮아.'],
        endingLines: ['짧게 물어봐도 괜찮아.', '부담 없을 때 해도 돼.'],
      },
      {
        choiceIntentId: 'school_later',
        text: '나중에 들을래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['hesitation_to_share'],
        protectiveFactors: ['sets_boundary'],
        responseLines: ['지금 바로 듣지 않아도 괜찮아.'],
        endingLines: ['나중에 들어도 괜찮아.', '오늘은 다른 걸 해봐도 좋아.'],
      },
    ],
  },
  worry_01: {
    nodeId: 'worry_01',
    questionText: '어떤 게 제일 신경 쓰여?',
    choices: [
      {
        choiceIntentId: 'worry_hospital',
        text: '병원 일이 걱정돼요',
        nextNodeId: 'hospital_02',
        intensity: 2,
        concernFlags: ['hospital_worry'],
        protectiveFactors: ['worry_named'],
        responseLines: ['병원 일이 신경 쓰일 수 있어.', '말하기 싫으면 괜찮다고 해도 돼.'],
      },
      {
        choiceIntentId: 'worry_family',
        text: '가족이 걱정돼요',
        nextNodeId: 'family_worry_02',
        intensity: 3,
        concernFlags: ['family_worry'],
        protectiveFactors: ['relationship_named'],
        responseLines: ['가족이 걱정될 때도 있지.', '혼자만 걱정하지 않아도 돼.'],
      },
      {
        choiceIntentId: 'worry_upset',
        text: '속상한 일이 있어요',
        nextNodeId: 'anger_02',
        intensity: 2,
        concernFlags: ['anger_or_frustration'],
        protectiveFactors: ['emotion_named'],
        responseLines: ['속상한 일이 있었구나.', '지금 바로 다 말하지 않아도 돼.'],
      },
    ],
  },
  hospital_02: {
    nodeId: 'hospital_02',
    questionText: '어떤 게 조금 걸려?',
    choices: [
      {
        choiceIntentId: 'hospital_shot_worry',
        text: '주사가 걱정돼요',
        nextNodeId: 'hospital_support_03',
        intensity: 3,
        concernFlags: ['procedure_fear', 'pain_concern'],
        protectiveFactors: ['can_name_fear'],
        responseLines: ['그럴 수 있어.', '주사 생각만 해도 걱정될 때가 있지.'],
      },
      {
        choiceIntentId: 'hospital_unknown_worry',
        text: '어떻게 하는지 모르겠어요',
        nextNodeId: 'hospital_question_03',
        intensity: 2,
        concernFlags: ['uncertainty', 'information_need'],
        protectiveFactors: ['uncertainty_named'],
        responseLines: ['모르면 더 걱정될 수 있어.', '물어보는 건 괜찮은 일이야.'],
      },
      {
        choiceIntentId: 'hospital_now_okay',
        text: '지금은 괜찮아요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['positive_mood'],
        responseLines: ['좋아. 지금은 괜찮구나.', '말하고 싶지 않으면 넘어가도 괜찮아.'],
        endingLines: ['오늘은 네 속도대로 가도 괜찮아.'],
      },
    ],
  },
  hospital_support_03: {
    nodeId: 'hospital_support_03',
    questionText: '그럴 땐 뭐가 조금 나을까?',
    choices: [
      {
        choiceIntentId: 'procedure_family_near',
        text: '가족이 옆에 있으면 좋아요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['family_support_preference', 'support_need_named'],
        responseLines: ['가족이 옆에 있으면 조금 든든할 수 있어.', '그렇게 부탁해도 괜찮아.'],
        endingLines: ['걱정될 땐 곁에 있어달라고 해도 돼.', '오늘은 천천히 가자.'],
      },
      {
        choiceIntentId: 'procedure_teacher_near',
        text: '선생님이 설명해주면 좋아요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['medical_support_preference', 'information_seeking'],
        responseLines: ['설명을 들으면 덜 낯설 수 있어.', '모르는 건 물어봐도 돼.'],
        endingLines: ['궁금한 건 물어봐도 괜찮아.', '활동은 천천히 해도 돼.'],
      },
      {
        choiceIntentId: 'procedure_hold_hand',
        text: '손을 잡아줬으면 해요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['needs_comfort'],
        protectiveFactors: ['comfort_preference_named'],
        responseLines: ['손을 잡아달라고 말해도 괜찮아.', '혼자 견디지 않아도 돼.'],
        endingLines: ['도움을 부탁해도 괜찮아.', '지금은 천천히 쉬어가자.'],
      },
    ],
  },
  hospital_question_03: {
    nodeId: 'hospital_question_03',
    questionText: '누구에게 물어보면 좋을까?',
    choices: [
      {
        choiceIntentId: 'procedure_ask_teacher',
        text: '선생님께 물어볼래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['information_seeking', 'medical_support_preference'],
        responseLines: ['좋아. 선생님께 물어보면 차근차근 알려줄 수 있어.'],
        endingLines: ['모르는 건 물어봐도 괜찮아.', '알고 나면 마음이 조금 편해질 수 있어.'],
      },
      {
        choiceIntentId: 'procedure_family_ask',
        text: '가족이랑 물어볼래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['family_support_preference', 'information_seeking'],
        responseLines: ['가족이랑 같이 물어보면 더 든든할 수 있어.'],
        endingLines: ['같이 물어보는 것도 좋은 방법이야.', '천천히 확인해도 돼.'],
      },
      {
        choiceIntentId: 'procedure_draw_question',
        text: '그림으로 물어볼래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: ['prefers_nonverbal_expression'],
        protectiveFactors: ['alternative_expression', 'creative_expression'],
        responseLines: ['그림으로 물어봐도 괜찮아.', '말보다 쉬울 때가 있지.'],
        endingLines: ['말이 어려우면 그림으로 해도 돼.', '오늘은 미술 활동으로 남겨봐도 좋아.'],
      },
    ],
  },
  family_worry_02: {
    nodeId: 'family_worry_02',
    questionText: '그럴 땐 누구에게 말하면 좋을까?',
    choices: [
      {
        choiceIntentId: 'family_say_worry',
        text: '가족에게 말할래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['verbal_expression', 'family_support_preference'],
        responseLines: ['좋아. 걱정된다고 말해도 괜찮아.', '말하면 조금 가벼워질 수 있어.'],
        endingLines: ['혼자 걱정하지 않아도 돼.', '짧게 말해도 괜찮아.'],
      },
      {
        choiceIntentId: 'family_tell_teacher',
        text: '선생님께 말할래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: [],
        protectiveFactors: ['medical_support_preference', 'support_seeking'],
        responseLines: ['선생님께 말하면 같이 도와줄 수 있어.', '혼자만 들고 있지 않아도 돼.'],
        endingLines: ['가까운 사람에게 말해보자.', '활동은 천천히 해도 괜찮아.'],
      },
      {
        choiceIntentId: 'family_show_drawing',
        text: '그림으로 보여줄래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 0,
        concernFlags: ['prefers_nonverbal_expression'],
        protectiveFactors: ['creative_expression', 'alternative_expression'],
        responseLines: ['그림으로 보여줘도 괜찮아.', '네 방식대로 전해도 돼.'],
        endingLines: ['말이 어려우면 그림으로 해도 돼.', '오늘은 미술 활동으로 남겨봐도 좋아.'],
      },
    ],
  },
  anger_02: {
    nodeId: 'anger_02',
    questionText: '그럴 땐 어떻게 하고 싶어?',
    choices: [
      {
        choiceIntentId: 'anger_pause',
        text: '잠깐 멈출래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['anger_or_frustration'],
        protectiveFactors: ['pause_coping', 'self_regulation'],
        responseLines: ['좋아. 잠깐 멈추는 것도 방법이야.', '천천히 다시 해도 돼.'],
        activityEndingLines: {
          pending: ['잠깐 쉬고 나서, 괜찮아지면 가벼운 활동 하나만 해보자.'],
          completed: ['오늘은 천천히 쉬어가자.'],
        },
      },
      {
        choiceIntentId: 'anger_say_upset',
        text: '속상하다고 말할래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['anger_or_frustration'],
        protectiveFactors: ['emotion_named', 'verbal_expression'],
        responseLines: ['속상하다고 말해도 괜찮아.', '말하면 조금 덜 답답할 수 있어.'],
        endingLines: ['가까운 사람에게 말해도 괜찮아.', '혼자 들고 있지 않아도 돼.'],
      },
      {
        choiceIntentId: 'anger_call_help',
        text: '도와달라고 말할래요',
        nextNodeId: null,
        endAfterSelect: true,
        intensity: 1,
        concernFlags: ['anger_or_frustration'],
        protectiveFactors: ['support_seeking', 'self_regulation'],
        responseLines: [
          '혼자 하기 어려울 땐 도와달라고 말해도 괜찮아.',
          '도움을 받는 것도 좋은 방법이야.',
        ],
        endingLines: ['먼저 도움을 받아도 괜찮아.', '그다음에 천천히 해도 돼.'],
      },
    ],
  },
}

const RAW_SHARED_COUNSELING_SCRIPTS: CounselingScript[] = [
  {
    scriptId: 'villager_entry_body',
    title: '가벼운 입구 대화',
    domain: 'body',
    weight: 3,
    startNodeId: 'entry_01',
    nodes: ENTRY_COUNSELING_NODES,
  },
  {
    scriptId: 'villager_entry_rest',
    title: '가벼운 휴식 입구 대화',
    domain: 'fatigue',
    weight: 2,
    startNodeId: 'entry_01',
    nodes: ENTRY_COUNSELING_NODES,
  },
  {
    scriptId: 'villager_entry_peer',
    title: '가벼운 친구 입구 대화',
    domain: 'peer',
    weight: 2,
    startNodeId: 'entry_01',
    nodes: ENTRY_COUNSELING_NODES,
  },
  {
    scriptId: 'villager_entry_family',
    title: '가벼운 마음 입구 대화',
    domain: 'family',
    weight: 1,
    startNodeId: 'entry_01',
    nodes: ENTRY_COUNSELING_NODES,
  },
  {
    scriptId: 'villager_entry_expression',
    title: '가벼운 표현 입구 대화',
    domain: 'expression',
    weight: 1,
    startNodeId: 'entry_01',
    nodes: ENTRY_COUNSELING_NODES,
  },
  {
    scriptId: 'villager_entry_worry',
    title: '가벼운 걱정 입구 대화',
    domain: 'anger',
    weight: 1,
    startNodeId: 'entry_01',
    nodes: ENTRY_COUNSELING_NODES,
  },
]

export const SHARED_COUNSELING_SCRIPTS: CounselingScript[] = applyActivityAwareEndingTypes(
  RAW_SHARED_COUNSELING_SCRIPTS,
)

export function pickRandomCounselingScript(scripts: CounselingScript[]) {
  if (scripts.length === 0) {
    throw new Error('No counseling scripts available')
  }

  const today = new Date().toISOString().slice(0, 10)
  const key = `recent_shared_counseling_script_${today}`
  const recentScriptId = localStorage.getItem(key)

  const candidates =
    scripts.length > 1 ? scripts.filter(script => script.scriptId !== recentScriptId) : scripts
  const pool = candidates.length > 0 ? candidates : scripts
  const totalWeight = pool.reduce((sum, script) => sum + (script.weight ?? 1), 0)
  let random = Math.random() * totalWeight

  for (const script of pool) {
    random -= script.weight ?? 1
    if (random <= 0) {
      localStorage.setItem(key, script.scriptId)
      return script
    }
  }

  localStorage.setItem(key, pool[0].scriptId)
  return pool[0]
}
