import type { VillagerDialogueScript, VillagerNpcId } from './types'

export const villageDialogues: Record<VillagerNpcId, VillagerDialogueScript> = {
  nurse_bunny: {
    npcId: 'nurse_bunny',
    npcName: '간호사 조은',
    theme: '몸 상태와 도움 요청',
    greetingLine: '오늘 몸이 어떤지 같이 살펴볼까?',
    closingLine: '말해줘서 고마워. 몸이 보내는 신호는 중요해.',
    scenes: [
      {
        sceneId: 'nurse_bunny_01_body',
        questionText: '오늘 몸은 어때?',
        choices: [
          {
            choiceIntentId: 'nurse_body_okay',
            text: '괜찮아요',
            nextSceneId: 'nurse_bunny_02_help',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['positive_body_state'],
            npcResponse: '좋아. 괜찮다고 느끼는구나.',
          },
          {
            choiceIntentId: 'nurse_body_tired',
            text: '조금 피곤해요',
            nextSceneId: 'nurse_bunny_02_help',
            intensity: 2,
            concernFlags: ['fatigue_present', 'body_discomfort'],
            protectiveFactors: ['body_state_named'],
            npcResponse: '피곤하다고 말해줘서 고마워.',
          },
          {
            choiceIntentId: 'nurse_pain_worry',
            text: '아픈 게 걱정돼요',
            nextSceneId: 'nurse_bunny_02_help',
            intensity: 3,
            concernFlags: ['pain_concern', 'procedure_fear'],
            protectiveFactors: ['can_name_fear'],
            npcResponse: '아픈 게 걱정될 수 있어.',
          },
        ],
      },
      {
        sceneId: 'nurse_bunny_02_help',
        questionText: '불편하면 어떻게 할까?',
        choices: [
          {
            choiceIntentId: 'nurse_tell_joeun',
            text: '조은에게 말해요',
            nextSceneId: 'nurse_bunny_03_body_action',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['support_seeking', 'medical_support_preference'],
            npcResponse: '좋아. 나에게 말해도 괜찮아.',
          },
          {
            choiceIntentId: 'nurse_tell_teacher',
            text: '선생님께 말해요',
            nextSceneId: 'nurse_bunny_03_body_action',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['medical_support_preference', 'support_seeking'],
            npcResponse: '선생님께 말하는 것도 좋아.',
          },
          {
            choiceIntentId: 'nurse_point_body',
            text: '아픈 곳을 가리켜요',
            nextSceneId: 'nurse_bunny_03_body_action',
            intensity: 1,
            concernFlags: ['prefers_nonverbal_expression'],
            protectiveFactors: ['alternative_expression', 'body_state_named'],
            npcResponse: '말이 어려우면 가리켜도 괜찮아.',
          },
        ],
      },
      {
        sceneId: 'nurse_bunny_03_body_action',
        questionText: '지금 몸을 위해 뭘 할까?',
        choices: [
          {
            choiceIntentId: 'nurse_take_rest',
            text: '잠깐 쉬어요',
            nextSceneId: null,
            intensity: 1,
            concernFlags: ['needs_rest'],
            protectiveFactors: ['sets_boundary', 'rest_need_named'],
            npcResponse: '잠깐 쉬어도 괜찮아.',
          },
          {
            choiceIntentId: 'nurse_drink_water',
            text: '물을 마셔요',
            nextSceneId: null,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['self_care_action', 'agency_coping'],
            npcResponse: '좋아. 작은 돌봄도 도움이 돼.',
          },
          {
            choiceIntentId: 'nurse_slow_breath',
            text: '천천히 숨 쉬어요',
            nextSceneId: null,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['breathing_coping', 'agency_coping'],
            npcResponse: '천천히 숨 쉬어보자.',
          },
        ],
      },
    ],
  },

  sleepy_sheep: {
    npcId: 'sleepy_sheep',
    npcName: '건빈',
    theme: '피로와 휴식',
    greetingLine: '안녕? 오늘도 와줬구나',
    closingLine: '쉬고 싶은 마음도 잘 말해줬어.',
    scenes: [
      {
        sceneId: 'sleepy_sheep_01_tired',
        questionText: '오늘 많이 피곤해?',
        choices: [
          {
            choiceIntentId: 'sheep_not_tired',
            text: '괜찮아요',
            nextSceneId: 'sleepy_sheep_02_rest',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['positive_body_state'],
            npcResponse: '좋아. 괜찮게 느껴지는구나.',
          },
          {
            choiceIntentId: 'sheep_little_sleepy',
            text: '조금 졸려요',
            nextSceneId: 'sleepy_sheep_02_rest',
            intensity: 1,
            concernFlags: ['fatigue_present'],
            protectiveFactors: ['body_state_named'],
            npcResponse: '조금 졸린 날이구나.',
          },
          {
            choiceIntentId: 'sheep_very_tired',
            text: '많이 지쳤어요',
            nextSceneId: 'sleepy_sheep_02_rest',
            intensity: 3,
            concernFlags: ['fatigue_high', 'needs_rest'],
            protectiveFactors: ['body_state_named', 'rest_need_named'],
            npcResponse: '많이 지쳤다고 느끼는구나.',
          },
        ],
      },
      {
        sceneId: 'sleepy_sheep_02_rest',
        questionText: '쉬고 싶을 땐 뭐가 좋아?',
        choices: [
          {
            choiceIntentId: 'sheep_quiet_rest',
            text: '조용히 있을래요',
            nextSceneId: 'sleepy_sheep_03_night',
            intensity: 1,
            concernFlags: ['needs_rest'],
            protectiveFactors: ['sets_boundary'],
            npcResponse: '조용히 쉬는 것도 좋아.',
          },
          {
            choiceIntentId: 'sheep_close_eyes',
            text: '눈을 감을래요',
            nextSceneId: 'sleepy_sheep_03_night',
            intensity: 1,
            concernFlags: ['fatigue_present'],
            protectiveFactors: ['rest_need_named', 'self_care_action'],
            npcResponse: '눈을 감고 쉬어도 괜찮아.',
          },
          {
            choiceIntentId: 'sheep_near_family',
            text: '가족 옆에 있을래요',
            nextSceneId: 'sleepy_sheep_03_night',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['family_support_preference', 'support_seeking'],
            npcResponse: '가족 옆이 편하게 느껴지는구나.',
          },
        ],
      },
      {
        sceneId: 'sleepy_sheep_03_night',
        questionText: '밤이 되면 마음은 어때?',
        choices: [
          {
            choiceIntentId: 'sheep_night_okay',
            text: '괜찮아요',
            nextSceneId: null,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['calm_state_named'],
            npcResponse: '괜찮은 밤이면 좋겠다.',
          },
          {
            choiceIntentId: 'sheep_night_worry',
            text: '걱정이 나요',
            nextSceneId: null,
            intensity: 2,
            concernFlags: ['sleep_worry', 'worry_present'],
            protectiveFactors: ['emotion_named'],
            npcResponse: '밤에는 걱정이 더 떠오를 수 있어.',
          },
          {
            choiceIntentId: 'sheep_night_lonely',
            text: '외로워요',
            nextSceneId: null,
            intensity: 2,
            concernFlags: ['loneliness', 'sleep_worry'],
            protectiveFactors: ['emotion_named'],
            npcResponse: '외로운 마음도 말해줘서 고마워.',
          },
        ],
      },
    ],
  },

  gardener_bear: {
    npcId: 'gardener_bear',
    npcName: '정호',
    theme: '마음 표현과 작은 대처',
    greetingLine: '오늘 마음을 어떻게 표현할지 같이 생각해보자.',
    closingLine: '네 마음을 전해줘서 고마워.',
    scenes: [
      {
        sceneId: 'gardener_bear_01_expression',
        questionText: '오늘 마음을 어떻게 보여줄까?',
        choices: [
          {
            choiceIntentId: 'bear_tell_words',
            text: '말로 해볼래요',
            nextSceneId: 'gardener_bear_02_heavy_mind',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['verbal_expression', 'support_seeking'],
            npcResponse: '말로 해보려는 마음이 있구나.',
          },
          {
            choiceIntentId: 'bear_draw_picture',
            text: '그림으로 해볼래요',
            nextSceneId: 'gardener_bear_02_heavy_mind',
            intensity: 0,
            concernFlags: ['prefers_nonverbal_expression'],
            protectiveFactors: ['creative_expression', 'alternative_expression'],
            npcResponse: '그림도 마음을 보여줄 수 있어.',
          },
          {
            choiceIntentId: 'bear_not_sure',
            text: '아직 잘 모르겠어요',
            nextSceneId: 'gardener_bear_02_heavy_mind',
            intensity: 2,
            concernFlags: ['uncertainty'],
            protectiveFactors: ['uncertainty_named'],
            npcResponse: '잘 모르겠다고 말해도 괜찮아.',
          },
        ],
      },
      {
        sceneId: 'gardener_bear_02_heavy_mind',
        questionText: '마음이 무거우면 뭘 해볼까?',
        choices: [
          {
            choiceIntentId: 'bear_slow_breath',
            text: '숨을 천천히 쉬어요',
            nextSceneId: 'gardener_bear_03_share',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['breathing_coping', 'agency_coping'],
            npcResponse: '천천히 숨 쉬면 조금 가벼워질 수 있어.',
          },
          {
            choiceIntentId: 'bear_draw_small',
            text: '작게 그려봐요',
            nextSceneId: 'gardener_bear_03_share',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['creative_expression', 'agency_coping'],
            npcResponse: '작게 그려보는 것도 좋아.',
          },
          {
            choiceIntentId: 'bear_ask_help',
            text: '도움을 말해요',
            nextSceneId: 'gardener_bear_03_share',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['support_seeking', 'agency_coping'],
            npcResponse: '도움을 말하는 건 좋은 방법이야.',
          },
        ],
      },
      {
        sceneId: 'gardener_bear_03_share',
        questionText: '누구에게 보여줄까?',
        choices: [
          {
            choiceIntentId: 'bear_show_family',
            text: '가족에게요',
            nextSceneId: null,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['family_support_preference', 'support_seeking'],
            npcResponse: '가족에게 보여줘도 괜찮아.',
          },
          {
            choiceIntentId: 'bear_show_teacher',
            text: '선생님에게요',
            nextSceneId: null,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['medical_support_preference', 'support_seeking'],
            npcResponse: '선생님도 들어줄 수 있어.',
          },
          {
            choiceIntentId: 'bear_keep_drawing',
            text: '그림으로만요',
            nextSceneId: null,
            intensity: 0,
            concernFlags: ['prefers_nonverbal_expression'],
            protectiveFactors: ['alternative_expression', 'creative_expression'],
            npcResponse: '말 대신 그림이어도 괜찮아.',
          },
        ],
      },
    ],
  },

  monkey_friend: {
    npcId: 'monkey_friend',
    npcName: '코몽',
    theme: '기분 전환과 감정 조절',
    greetingLine: '기분을 조금 바꿔볼 방법을 찾아볼까?',
    closingLine: '작은 놀이도 마음에 힘이 될 수 있어.',
    scenes: [
      {
        sceneId: 'monkey_friend_01_move',
        questionText: '지금 움직이고 싶어?',
        choices: [
          {
            choiceIntentId: 'monkey_move_little',
            text: '조금 움직일래요',
            nextSceneId: 'monkey_friend_02_mood_change',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['playful_coping', 'agency_coping'],
            npcResponse: '좋아. 조금만 움직여보자.',
          },
          {
            choiceIntentId: 'monkey_stay_still',
            text: '가만히 있을래요',
            nextSceneId: 'monkey_friend_02_mood_change',
            intensity: 1,
            concernFlags: ['needs_rest'],
            protectiveFactors: ['sets_boundary'],
            npcResponse: '가만히 있어도 괜찮아.',
          },
          {
            choiceIntentId: 'monkey_not_sure',
            text: '잘 모르겠어요',
            nextSceneId: 'monkey_friend_02_mood_change',
            intensity: 1,
            concernFlags: ['uncertainty'],
            protectiveFactors: ['uncertainty_named'],
            npcResponse: '잘 모를 때도 있어.',
          },
        ],
      },
      {
        sceneId: 'monkey_friend_02_mood_change',
        questionText: '기분을 바꾸려면 뭐가 좋을까?',
        choices: [
          {
            choiceIntentId: 'monkey_short_play',
            text: '짧게 놀래요',
            nextSceneId: 'monkey_friend_03_angry',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['playful_coping', 'positive_activity'],
            npcResponse: '짧은 놀이도 도움이 될 수 있어.',
          },
          {
            choiceIntentId: 'monkey_look_picture',
            text: '그림을 볼래요',
            nextSceneId: 'monkey_friend_03_angry',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['creative_expression', 'positive_activity'],
            npcResponse: '그림을 보는 것도 좋은 기분 전환이야.',
          },
          {
            choiceIntentId: 'monkey_breathe',
            text: '숨을 쉬어볼래요',
            nextSceneId: 'monkey_friend_03_angry',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['breathing_coping'],
            npcResponse: '좋아. 천천히 숨 쉬어보자.',
          },
        ],
      },
      {
        sceneId: 'monkey_friend_03_angry',
        questionText: '화가 날 땐 어떻게 할까?',
        choices: [
          {
            choiceIntentId: 'monkey_pause',
            text: '잠깐 멈춰요',
            nextSceneId: null,
            intensity: 1,
            concernFlags: ['anger_or_frustration'],
            protectiveFactors: ['pause_coping', 'self_regulation'],
            npcResponse: '잠깐 멈추는 것도 좋은 방법이야.',
          },
          {
            choiceIntentId: 'monkey_say_upset',
            text: '속상하다고 말해요',
            nextSceneId: null,
            intensity: 1,
            concernFlags: ['anger_or_frustration'],
            protectiveFactors: ['emotion_named', 'verbal_expression'],
            npcResponse: '속상하다고 말해도 괜찮아.',
          },
          {
            choiceIntentId: 'monkey_call_help',
            text: '도움을 불러요',
            nextSceneId: null,
            intensity: 1,
            concernFlags: ['anger_or_frustration'],
            protectiveFactors: ['support_seeking', 'self_regulation'],
            npcResponse: '도움이 필요하면 불러도 괜찮아.',
          },
        ],
      },
    ],
  },

  squirrel_friend: {
    npcId: 'squirrel_friend',
    npcName: '세현',
    theme: '걱정과 관계',
    greetingLine: '작은 걱정도 같이 들어볼게.',
    closingLine: '네가 고른 마음을 잘 기억해둘게.',
    scenes: [
      {
        sceneId: 'squirrel_friend_01_worry',
        questionText: '오늘 걱정은 뭐야?',
        choices: [
          {
            choiceIntentId: 'squirrel_worry_pain',
            text: '아픈 게 걱정돼요',
            nextSceneId: 'squirrel_friend_02_near',
            intensity: 3,
            concernFlags: ['pain_concern', 'procedure_fear'],
            protectiveFactors: ['can_name_fear'],
            npcResponse: '아픈 게 걱정될 수 있어.',
          },
          {
            choiceIntentId: 'squirrel_worry_family',
            text: '가족이 걱정돼요',
            nextSceneId: 'squirrel_friend_02_near',
            intensity: 3,
            concernFlags: ['parent_concern', 'family_worry'],
            protectiveFactors: ['empathy', 'relationship_named'],
            npcResponse: '가족을 많이 생각하고 있었구나.',
          },
          {
            choiceIntentId: 'squirrel_worry_unknown',
            text: '잘 모르겠어요',
            nextSceneId: 'squirrel_friend_02_near',
            intensity: 2,
            concernFlags: ['uncertainty', 'worry_present'],
            protectiveFactors: ['uncertainty_named'],
            npcResponse: '이유를 몰라도 걱정은 생길 수 있어.',
          },
        ],
      },
      {
        sceneId: 'squirrel_friend_02_near',
        questionText: '누가 옆에 있으면 좋겠어?',
        choices: [
          {
            choiceIntentId: 'squirrel_need_family',
            text: '가족이 좋아요',
            nextSceneId: 'squirrel_friend_03_friend',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['family_support_preference', 'support_need_named'],
            npcResponse: '가족이 곁에 있으면 편하구나.',
          },
          {
            choiceIntentId: 'squirrel_need_teacher',
            text: '선생님이 좋아요',
            nextSceneId: 'squirrel_friend_03_friend',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['medical_support_preference', 'support_need_named'],
            npcResponse: '선생님도 곁에 있어줄 수 있어.',
          },
          {
            choiceIntentId: 'squirrel_need_alone',
            text: '혼자 쉬고 싶어요',
            nextSceneId: 'squirrel_friend_03_friend',
            intensity: 1,
            concernFlags: ['needs_rest'],
            protectiveFactors: ['sets_boundary'],
            npcResponse: '혼자 쉬고 싶은 마음도 괜찮아.',
          },
        ],
      },
      {
        sceneId: 'squirrel_friend_03_friend',
        questionText: '친구 생각은 어때?',
        choices: [
          {
            choiceIntentId: 'squirrel_miss_friend',
            text: '보고 싶어요',
            nextSceneId: null,
            intensity: 2,
            concernFlags: ['peer_separation', 'loneliness'],
            protectiveFactors: ['relationship_named'],
            npcResponse: '친구가 보고 싶었구나.',
          },
          {
            choiceIntentId: 'squirrel_friend_okay',
            text: '지금은 괜찮아요',
            nextSceneId: null,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['positive_social_state'],
            npcResponse: '지금은 괜찮게 느껴지는구나.',
          },
          {
            choiceIntentId: 'squirrel_friend_lonely',
            text: '조금 외로워요',
            nextSceneId: null,
            intensity: 2,
            concernFlags: ['loneliness', 'peer_separation'],
            protectiveFactors: ['emotion_named'],
            npcResponse: '외로운 마음도 말해도 괜찮아.',
          },
        ],
      },
    ],
  },

  dain: {
    npcId: 'dain',
    npcName: '다인',
    theme: '또래 관계와 마음 전하기',
    greetingLine: '오늘 마음을 나랑 살짝 나눠볼래?',
    closingLine: '말해줘서 고마워. 네 마음을 잘 기억할게.',
    scenes: [
      {
        sceneId: 'dain_01_friend',
        questionText: '친구 생각이 나니?',
        choices: [
          {
            choiceIntentId: 'dain_friend_much',
            text: '많이 생각나요',
            nextSceneId: 'dain_02_message',
            intensity: 2,
            concernFlags: ['peer_separation', 'loneliness'],
            protectiveFactors: ['relationship_named'],
            npcResponse: '친구 생각이 많이 났구나.',
          },
          {
            choiceIntentId: 'dain_friend_little',
            text: '조금 생각나요',
            nextSceneId: 'dain_02_message',
            intensity: 1,
            concernFlags: ['peer_separation'],
            protectiveFactors: ['relationship_named'],
            npcResponse: '친구가 조금 떠올랐구나.',
          },
          {
            choiceIntentId: 'dain_friend_okay',
            text: '괜찮아요',
            nextSceneId: 'dain_02_message',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['positive_social_state'],
            npcResponse: '지금은 괜찮게 느끼는구나.',
          },
        ],
      },
      {
        sceneId: 'dain_02_message',
        questionText: '마음을 전한다면?',
        choices: [
          {
            choiceIntentId: 'dain_short_hi',
            text: '짧게 인사해요',
            nextSceneId: 'dain_03_lonely',
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['verbal_expression', 'social_connection'],
            npcResponse: '짧은 인사도 마음을 전할 수 있어.',
          },
          {
            choiceIntentId: 'dain_send_drawing',
            text: '그림을 보내요',
            nextSceneId: 'dain_03_lonely',
            intensity: 0,
            concernFlags: ['prefers_nonverbal_expression'],
            protectiveFactors: ['alternative_expression', 'creative_expression'],
            npcResponse: '그림으로 마음을 전해도 좋아.',
          },
          {
            choiceIntentId: 'dain_talk_later',
            text: '나중에 말해요',
            nextSceneId: 'dain_03_lonely',
            intensity: 1,
            concernFlags: ['hesitation_to_share'],
            protectiveFactors: ['sets_boundary'],
            npcResponse: '나중에 말하고 싶어도 괜찮아.',
          },
        ],
      },
      {
        sceneId: 'dain_03_lonely',
        questionText: '외로울 땐 뭐가 좋아?',
        choices: [
          {
            choiceIntentId: 'dain_stay_together',
            text: '같이 있어줘요',
            nextSceneId: null,
            intensity: 2,
            concernFlags: ['loneliness', 'needs_connection'],
            protectiveFactors: ['support_need_named'],
            npcResponse: '같이 있어주길 바라는구나.',
          },
          {
            choiceIntentId: 'dain_call_name',
            text: '이름을 불러줘요',
            nextSceneId: null,
            intensity: 1,
            concernFlags: ['needs_connection'],
            protectiveFactors: ['support_need_named'],
            npcResponse: '이름을 불러주는 것도 따뜻하지.',
          },
          {
            choiceIntentId: 'dain_think_good_memory',
            text: '좋은 일을 떠올려요',
            nextSceneId: null,
            intensity: 0,
            concernFlags: [],
            protectiveFactors: ['positive_memory', 'agency_coping'],
            npcResponse: '좋은 기억이 마음을 도와줄 수 있어.',
          },
        ],
      },
    ],
  },
}
