import type { CSSProperties } from 'react'

export const authStyles: Record<string, CSSProperties> = {
  backdrop: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0, 0, 0, 0.55)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    backdropFilter: 'blur(4px)',
  },
  card: {
    position: 'relative',
    width: 380,
    maxWidth: 'calc(100vw - 32px)',
    padding: 28,
    background: 'rgba(255, 255, 255, 0.97)',
    borderRadius: 12,
    boxShadow: '0 12px 32px rgba(0, 0, 0, 0.35)',
  },
  closeButton: {
    position: 'absolute',
    top: 8,
    right: 12,
    background: 'transparent',
    border: 'none',
    fontSize: 22,
    lineHeight: 1,
    color: '#666',
    cursor: 'pointer',
    padding: 4,
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
  },
  title: {
    margin: '0 0 4px',
    fontSize: 22,
    textAlign: 'center',
    color: '#222',
  },
  label: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    fontSize: 14,
    color: '#333',
  },
  input: {
    padding: '9px 11px',
    fontSize: 14,
    border: '1px solid #ccc',
    borderRadius: 6,
    outline: 'none',
  },
  error: {
    color: '#d32f2f',
    fontSize: 12,
  },
  errorBox: {
    padding: 10,
    background: '#fdecea',
    color: '#d32f2f',
    borderRadius: 6,
    fontSize: 13,
  },
  primaryButton: {
    padding: '11px 14px',
    fontSize: 15,
    background: '#e8632a',
    color: '#fff',
    border: 'none',
    borderRadius: 6,
    cursor: 'pointer',
    fontWeight: 600,
  },
  linkButton: {
    background: 'transparent',
    border: 'none',
    color: '#1976d2',
    fontSize: 13,
    cursor: 'pointer',
    padding: 4,
    textAlign: 'center',
  },
}
