import type { CSSProperties } from 'react'

export const authStyles: Record<string, CSSProperties> = {
  backdrop: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(20, 12, 4, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  card: {
    position: 'relative',
    width: 380,
    maxWidth: 'calc(100vw - 32px)',
    padding: '28px 26px 22px',
    background: '#f3e1c1',
    border: '2px solid #5a3818',
    borderRadius: 14,
    boxShadow: '0 14px 32px rgba(0, 0, 0, 0.55), 0 4px 8px rgba(0, 0, 0, 0.25)',
    color: '#3a2410',
  },
  closeButton: {
    position: 'absolute',
    top: 8,
    right: 10,
    background: 'transparent',
    border: 'none',
    fontSize: 18,
    lineHeight: 1,
    color: '#5a3818',
    cursor: 'pointer',
    padding: 4,
  },
  title: {
    margin: '0 0 16px',
    fontSize: 20,
    fontWeight: 700,
    textAlign: 'center',
    color: '#5a3818',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  label: {
    display: 'flex',
    flexDirection: 'column',
    gap: 5,
    fontSize: 13,
    fontWeight: 500,
    color: '#5a3818',
  },
  input: {
    padding: '10px 12px',
    fontSize: 14,
    background: '#fbf3df',
    border: '1.5px solid #8b5a2b',
    borderRadius: 8,
    color: '#3a2410',
    outline: 'none',
    fontFamily: 'inherit',
  },
  error: {
    color: '#a02020',
    fontSize: 12,
  },
  errorBox: {
    padding: 10,
    background: '#f6d6c8',
    color: '#7a1818',
    border: '1.5px solid #c25a17',
    borderRadius: 8,
    fontSize: 13,
  },
  primaryButton: {
    marginTop: 4,
    padding: '11px 16px',
    fontSize: 15,
    fontWeight: 700,
    color: '#fff5d8',
    background: '#e8782a',
    border: '2px solid #6e3712',
    borderRadius: 10,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  linkButton: {
    background: 'transparent',
    border: 'none',
    color: '#5a3818',
    fontSize: 13,
    cursor: 'pointer',
    padding: 4,
    textAlign: 'center',
    fontFamily: 'inherit',
  },
  linkAction: {
    color: '#c25a17',
    fontWeight: 700,
    marginLeft: 4,
  },
}
