LEFT_SHOULDER = "LEFT_SHOULDER"
RIGHT_SHOULDER = "RIGHT_SHOULDER"
LEFT_HIP = "LEFT_HIP"
RIGHT_HIP = "RIGHT_HIP"
LEFT_ELBOW = "LEFT_ELBOW"
RIGHT_ELBOW = "RIGHT_ELBOW"
LEFT_WRIST = "LEFT_WRIST"
RIGHT_WRIST = "RIGHT_WRIST"
LEFT_KNEE = "LEFT_KNEE"
RIGHT_KNEE = "RIGHT_KNEE"
LEFT_ANKLE = "LEFT_ANKLE"
RIGHT_ANKLE = "RIGHT_ANKLE"

REQUIRED_SCALE_POINTS = (LEFT_SHOULDER, RIGHT_SHOULDER)
REQUIRED_CENTER_POINTS = (LEFT_HIP, RIGHT_HIP)
REQUIRED_TAEKWONDO_TRACKING_POINTS = (
    LEFT_SHOULDER,
    RIGHT_SHOULDER,
    LEFT_ELBOW,
    RIGHT_ELBOW,
    LEFT_WRIST,
    RIGHT_WRIST,
    LEFT_HIP,
    RIGHT_HIP,
    LEFT_KNEE,
    RIGHT_KNEE,
    LEFT_ANKLE,
    RIGHT_ANKLE,
)

DEFAULT_MIN_CONFIDENCE = 0.5
MIN_SCALE_REFERENCE = 1e-6
MIN_SAFE_SCALE_REFERENCE = 0.01
TRACKING_LOST_THRESHOLD = 0.5
TRACKING_CONFIDENCE_GOOD = 0.9
DEFAULT_CALIBRATION_TARGET_FRAMES = 5
MAX_CALIBRATION_TARGET_FRAMES = 100

ACTION_READY = "ready"
ACTION_LOW_BLOCK = "low_block"
ACTION_MIDDLE_PUNCH = "middle_punch"
ACTION_UNCLASSIFIED = "unclassified"

ACTION_LABELS = (
    ACTION_READY,
    ACTION_LOW_BLOCK,
    ACTION_MIDDLE_PUNCH,
)

MIN_CLASSIFICATION_CONFIDENCE = 0.45

FEATURE_WRIST_NEAR_HIP_DISTANCE_MAX = 0.45
FEATURE_DOMINANT_ACTION_MIN_SCORE = 0.8
FEATURE_DOMINANT_ACTION_MARGIN = 0.15

READY_HANDS_BALANCED_Y_DIFF_MAX = 0.25
READY_HANDS_NOT_EXTENDED_X_MAX = 0.45
READY_BOTH_NEAR_HIPS_WEIGHT = 0.4
READY_HANDS_BALANCED_WEIGHT = 0.25
READY_HANDS_NOT_EXTENDED_WEIGHT = 0.2
READY_ELBOWS_NOT_LOCKED_WEIGHT = 0.15

LOW_BLOCK_WRIST_Y_MIN = 0.25
LOW_BLOCK_FAR_FROM_CENTER_REFERENCE = 1.2
LOW_BLOCK_WRIST_LOW_WEIGHT = 0.35
LOW_BLOCK_FAR_FROM_CENTER_WEIGHT = 0.25
LOW_BLOCK_EXTENDED_ARM_WEIGHT = 0.25
LOW_BLOCK_OPPOSITE_NEAR_HIP_WEIGHT = 0.15

MIDDLE_PUNCH_WRIST_Y_MIN = -0.9
MIDDLE_PUNCH_WRIST_Y_MAX = -0.1
MIDDLE_PUNCH_FAR_FROM_CENTER_REFERENCE = 1.2
MIDDLE_PUNCH_TORSO_HEIGHT_WEIGHT = 0.35
MIDDLE_PUNCH_FAR_FROM_CENTER_WEIGHT = 0.25
MIDDLE_PUNCH_EXTENDED_ARM_WEIGHT = 0.25
MIDDLE_PUNCH_OPPOSITE_NEAR_HIP_WEIGHT = 0.15

ELBOW_EXTENDED_THRESHOLD = 150.0
ELBOW_SEMI_EXTENDED_THRESHOLD = 120.0
ELBOW_BENT_MIN = 60.0
ELBOW_BENT_MAX = 150.0
ELBOW_SLIGHTLY_BENT_MAX = 165.0
