LEFT_SHOULDER = "LEFT_SHOULDER"
RIGHT_SHOULDER = "RIGHT_SHOULDER"
LEFT_HIP = "LEFT_HIP"
RIGHT_HIP = "RIGHT_HIP"
LEFT_ELBOW = "LEFT_ELBOW"
RIGHT_ELBOW = "RIGHT_ELBOW"
LEFT_WRIST = "LEFT_WRIST"
RIGHT_WRIST = "RIGHT_WRIST"
LEFT_KNEE = "LEFT_KNEE"
RIGHT_KNEE = "RIGHT_KNEE"
LEFT_ANKLE = "LEFT_ANKLE"
RIGHT_ANKLE = "RIGHT_ANKLE"

REQUIRED_SCALE_POINTS = (LEFT_SHOULDER, RIGHT_SHOULDER)
REQUIRED_CENTER_POINTS = (LEFT_HIP, RIGHT_HIP)
REQUIRED_TAEKWONDO_TRACKING_POINTS = (
    LEFT_SHOULDER,
    RIGHT_SHOULDER,
    LEFT_ELBOW,
    RIGHT_ELBOW,
    LEFT_WRIST,
    RIGHT_WRIST,
    LEFT_HIP,
    RIGHT_HIP,
    LEFT_KNEE,
    RIGHT_KNEE,
    LEFT_ANKLE,
    RIGHT_ANKLE,
)

DEFAULT_MIN_CONFIDENCE = 0.5
MIN_SCALE_REFERENCE = 1e-6
MIN_SAFE_SCALE_REFERENCE = 0.01
TRACKING_LOST_THRESHOLD = 0.5
TRACKING_CONFIDENCE_GOOD = 0.9
DEFAULT_CALIBRATION_TARGET_FRAMES = 5
MAX_CALIBRATION_TARGET_FRAMES = 100

ACTION_READY = "ready"
ACTION_LOW_BLOCK = "low_block"
ACTION_MIDDLE_PUNCH = "middle_punch"
ACTION_UNCLASSIFIED = "unclassified"

ACTION_LABELS = (
    ACTION_READY,
    ACTION_LOW_BLOCK,
    ACTION_MIDDLE_PUNCH,
)
