server:
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: false

cors:
  allowed-origins:
    - https://k14e103.p.ssafy.io
    - https://game-dev.wish-e103.xyz
    - https://admin-dev.wish-e103.xyz
    - https://guardian-dev.wish-e103.xyz
    - http://localhost:3001
    - http://localhost:3002
    - http://localhost:3003
    - http://127.0.0.1:3001
    - http://127.0.0.1:3002
