LEFT_SHOULDER = "LEFT_SHOULDER"
RIGHT_SHOULDER = "RIGHT_SHOULDER"
LEFT_HIP = "LEFT_HIP"
RIGHT_HIP = "RIGHT_HIP"
LEFT_KNEE = "LEFT_KNEE"
RIGHT_KNEE = "RIGHT_KNEE"
LEFT_ANKLE = "LEFT_ANKLE"
RIGHT_ANKLE = "RIGHT_ANKLE"

REQUIRED_SCALE_POINTS = (LEFT_SHOULDER, RIGHT_SHOULDER)
REQUIRED_CENTER_POINTS = (LEFT_HIP, RIGHT_HIP)
REQUIRED_MARCH_TRACKING_POINTS = (LEFT_KNEE, RIGHT_KNEE, LEFT_ANKLE, RIGHT_ANKLE)

DEFAULT_MIN_CONFIDENCE = 0.5
MIN_SCALE_REFERENCE = 1e-6
NUMERIC_EPSILON = MIN_SCALE_REFERENCE

DEFAULT_MARCH_TARGET_STEPS = 8

DEFAULT_MARCH_THIGH_ANGLE_THRESHOLD = 25.0

DEFAULT_MARCH_DOMINANCE_MARGIN = 3.0

DEFAULT_MARCH_RELEASE_THRESHOLD = 25.0

DEFAULT_MARCH_TORSO_TILT_MAX = 12.0

DEFAULT_MARCH_PELVIS_SHIFT_MAX = 0.30

DEFAULT_MARCH_DEPTH_SHIFT_MAX = 0.40

DEFAULT_FEEDBACK_STREAK_THRESHOLD = 8
DEFAULT_FEEDBACK_DISPLAY_FRAMES = 60
DEFAULT_FEEDBACK_CLEAR_FRAMES = 5

MARCH_MOTION_NAME = "\uc81c\uc790\ub9ac \uac77\uae30"
SIDE_STEP_MOTION_NAME = "\uc0ac\uc774\ub4dc \uc2a4\ud15d"

DEFAULT_SIDE_STEP_TARGET_STEPS = 8
DEFAULT_SIDE_STEP_EXTENT_THRESHOLD = 0.35
DEFAULT_SIDE_STEP_ANKLE_SPAN_THRESHOLD = 0.45
DEFAULT_SIDE_STEP_DOMINANCE_MARGIN = 0.10
DEFAULT_SIDE_STEP_RELEASE_THRESHOLD = 0.12
DEFAULT_SIDE_STEP_TORSO_TILT_MAX = 12.0
DEFAULT_SIDE_STEP_DEPTH_SHIFT_MAX = 0.40
