LEFT_SHOULDER = "LEFT_SHOULDER"
RIGHT_SHOULDER = "RIGHT_SHOULDER"
LEFT_HIP = "LEFT_HIP"
RIGHT_HIP = "RIGHT_HIP"

REQUIRED_SCALE_POINTS = (LEFT_SHOULDER, RIGHT_SHOULDER)
REQUIRED_CENTER_POINTS = (LEFT_HIP, RIGHT_HIP)

DEFAULT_MIN_CONFIDENCE = 0.5
MIN_SCALE_REFERENCE = 1e-6
